//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.gob.sat.cfdi.ecc11;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Conceptos">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="ConceptoEstadoDeCuentaCombustible" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="Traslados">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     <sequence>
 *                                       <element name="Traslado" maxOccurs="unbounded">
 *                                         <complexType>
 *                                           <complexContent>
 *                                             <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               <attribute name="Impuesto" use="required">
 *                                                 <simpleType>
 *                                                   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                     <whiteSpace value="collapse"/>
 *                                                     <enumeration value="IVA"/>
 *                                                     <enumeration value="IEPS"/>
 *                                                   </restriction>
 *                                                 </simpleType>
 *                                               </attribute>
 *                                               <attribute name="TasaoCuota" use="required">
 *                                                 <simpleType>
 *                                                   <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                                     <fractionDigits value="6"/>
 *                                                     <whiteSpace value="collapse"/>
 *                                                   </restriction>
 *                                                 </simpleType>
 *                                               </attribute>
 *                                               <attribute name="Importe" use="required">
 *                                                 <simpleType>
 *                                                   <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                                     <fractionDigits value="2"/>
 *                                                     <whiteSpace value="collapse"/>
 *                                                     <minInclusive value="0.01"/>
 *                                                     <pattern value="[0-9]{1,14}(.([0-9]{1,2}))"/>
 *                                                   </restriction>
 *                                                 </simpleType>
 *                                               </attribute>
 *                                             </restriction>
 *                                           </complexContent>
 *                                         </complexType>
 *                                       </element>
 *                                     </sequence>
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                           </sequence>
 *                           <attribute name="Identificador" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <minLength value="1"/>
 *                                 <whiteSpace value="collapse"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Fecha" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *                                 <whiteSpace value="collapse"/>
 *                                 <minInclusive value="2015-01-01T00:00:00"/>
 *                                 <pattern value="([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Rfc" use="required" type="{http://www.sat.gob.mx/EstadoDeCuentaCombustible}t_RFC" />
 *                           <attribute name="ClaveEstacion" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <whiteSpace value="collapse"/>
 *                                 <minLength value="1"/>
 *                                 <maxLength value="10"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="TAR" type="{http://www.sat.gob.mx/EstadoDeCuentaCombustible}c_TAR" />
 *                           <attribute name="Cantidad" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 <minInclusive value="0.001"/>
 *                                 <fractionDigits value="3"/>
 *                                 <whiteSpace value="collapse"/>
 *                                 <pattern value="[0-9]{1,14}(.([0-9]{1,3}))"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="NoIdentificacion" use="required" type="{http://www.sat.gob.mx/EstadoDeCuentaCombustible}c_claveProducto" />
 *                           <attribute name="Unidad">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <whiteSpace value="collapse"/>
 *                                 <minLength value="1"/>
 *                                 <maxLength value="25"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="NombreCombustible" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <whiteSpace value="collapse"/>
 *                                 <minLength value="1"/>
 *                                 <maxLength value="300"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="FolioOperacion" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <whiteSpace value="collapse"/>
 *                                 <minLength value="1"/>
 *                                 <maxLength value="50"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="ValorUnitario" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 <minInclusive value="0.001"/>
 *                                 <fractionDigits value="3"/>
 *                                 <whiteSpace value="collapse"/>
 *                                 <pattern value="[0-9]{1,14}(.([0-9]{1,3}))"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Importe" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 <fractionDigits value="2"/>
 *                                 <whiteSpace value="collapse"/>
 *                                 <pattern value="[0-9]{1,14}(.([0-9]{1,2}))"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attribute name="Version" use="required" fixed="1.1">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="TipoOperacion" use="required" fixed="Tarjeta">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="NumeroDeCuenta" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="50"/>
 *             <whiteSpace value="collapse"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="SubTotal" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             <fractionDigits value="2"/>
 *             <whiteSpace value="collapse"/>
 *             <pattern value="[0-9]{1,14}(.([0-9]{1,2}))"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="Total" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             <fractionDigits value="2"/>
 *             <whiteSpace value="collapse"/>
 *             <pattern value="[0-9]{1,14}(.([0-9]{1,2}))"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "conceptos"
})
@XmlRootElement(name = "EstadoDeCuentaCombustible")
public class EstadoDeCuentaCombustible
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "Conceptos", required = true)
    protected EstadoDeCuentaCombustible.Conceptos conceptos;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "TipoOperacion", required = true)
    protected String tipoOperacion;
    @XmlAttribute(name = "NumeroDeCuenta", required = true)
    protected String numeroDeCuenta;
    @XmlAttribute(name = "SubTotal", required = true)
    protected BigDecimal subTotal;
    @XmlAttribute(name = "Total", required = true)
    protected BigDecimal total;

    /**
     * Gets the value of the conceptos property.
     * 
     * @return
     *     possible object is
     *     {@link EstadoDeCuentaCombustible.Conceptos }
     *     
     */
    public EstadoDeCuentaCombustible.Conceptos getConceptos() {
        return conceptos;
    }

    /**
     * Sets the value of the conceptos property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstadoDeCuentaCombustible.Conceptos }
     *     
     */
    public void setConceptos(EstadoDeCuentaCombustible.Conceptos value) {
        this.conceptos = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.1";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the tipoOperacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoOperacion() {
        if (tipoOperacion == null) {
            return "Tarjeta";
        } else {
            return tipoOperacion;
        }
    }

    /**
     * Sets the value of the tipoOperacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoOperacion(String value) {
        this.tipoOperacion = value;
    }

    /**
     * Gets the value of the numeroDeCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroDeCuenta() {
        return numeroDeCuenta;
    }

    /**
     * Sets the value of the numeroDeCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroDeCuenta(String value) {
        this.numeroDeCuenta = value;
    }

    /**
     * Gets the value of the subTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubTotal() {
        return subTotal;
    }

    /**
     * Sets the value of the subTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubTotal(BigDecimal value) {
        this.subTotal = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotal(BigDecimal value) {
        this.total = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="ConceptoEstadoDeCuentaCombustible" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="Traslados">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           <sequence>
     *                             <element name="Traslado" maxOccurs="unbounded">
     *                               <complexType>
     *                                 <complexContent>
     *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     <attribute name="Impuesto" use="required">
     *                                       <simpleType>
     *                                         <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                           <whiteSpace value="collapse"/>
     *                                           <enumeration value="IVA"/>
     *                                           <enumeration value="IEPS"/>
     *                                         </restriction>
     *                                       </simpleType>
     *                                     </attribute>
     *                                     <attribute name="TasaoCuota" use="required">
     *                                       <simpleType>
     *                                         <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                                           <fractionDigits value="6"/>
     *                                           <whiteSpace value="collapse"/>
     *                                         </restriction>
     *                                       </simpleType>
     *                                     </attribute>
     *                                     <attribute name="Importe" use="required">
     *                                       <simpleType>
     *                                         <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                                           <fractionDigits value="2"/>
     *                                           <whiteSpace value="collapse"/>
     *                                           <minInclusive value="0.01"/>
     *                                           <pattern value="[0-9]{1,14}(.([0-9]{1,2}))"/>
     *                                         </restriction>
     *                                       </simpleType>
     *                                     </attribute>
     *                                   </restriction>
     *                                 </complexContent>
     *                               </complexType>
     *                             </element>
     *                           </sequence>
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                 </sequence>
     *                 <attribute name="Identificador" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <minLength value="1"/>
     *                       <whiteSpace value="collapse"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Fecha" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
     *                       <whiteSpace value="collapse"/>
     *                       <minInclusive value="2015-01-01T00:00:00"/>
     *                       <pattern value="([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Rfc" use="required" type="{http://www.sat.gob.mx/EstadoDeCuentaCombustible}t_RFC" />
     *                 <attribute name="ClaveEstacion" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <whiteSpace value="collapse"/>
     *                       <minLength value="1"/>
     *                       <maxLength value="10"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="TAR" type="{http://www.sat.gob.mx/EstadoDeCuentaCombustible}c_TAR" />
     *                 <attribute name="Cantidad" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       <minInclusive value="0.001"/>
     *                       <fractionDigits value="3"/>
     *                       <whiteSpace value="collapse"/>
     *                       <pattern value="[0-9]{1,14}(.([0-9]{1,3}))"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="NoIdentificacion" use="required" type="{http://www.sat.gob.mx/EstadoDeCuentaCombustible}c_claveProducto" />
     *                 <attribute name="Unidad">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <whiteSpace value="collapse"/>
     *                       <minLength value="1"/>
     *                       <maxLength value="25"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="NombreCombustible" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <whiteSpace value="collapse"/>
     *                       <minLength value="1"/>
     *                       <maxLength value="300"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="FolioOperacion" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <whiteSpace value="collapse"/>
     *                       <minLength value="1"/>
     *                       <maxLength value="50"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="ValorUnitario" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       <minInclusive value="0.001"/>
     *                       <fractionDigits value="3"/>
     *                       <whiteSpace value="collapse"/>
     *                       <pattern value="[0-9]{1,14}(.([0-9]{1,3}))"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Importe" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       <fractionDigits value="2"/>
     *                       <whiteSpace value="collapse"/>
     *                       <pattern value="[0-9]{1,14}(.([0-9]{1,2}))"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "conceptoEstadoDeCuentaCombustible"
    })
    public static class Conceptos
        implements Serializable
    {

        private static final long serialVersionUID = 1L;
        @XmlElement(name = "ConceptoEstadoDeCuentaCombustible", required = true)
        protected List<EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible> conceptoEstadoDeCuentaCombustible;

        /**
         * Gets the value of the conceptoEstadoDeCuentaCombustible property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the conceptoEstadoDeCuentaCombustible property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConceptoEstadoDeCuentaCombustible().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible }
         * 
         * 
         * @return
         *     The value of the conceptoEstadoDeCuentaCombustible property.
         */
        public List<EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible> getConceptoEstadoDeCuentaCombustible() {
            if (conceptoEstadoDeCuentaCombustible == null) {
                conceptoEstadoDeCuentaCombustible = new ArrayList<>();
            }
            return this.conceptoEstadoDeCuentaCombustible;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="Traslados">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 <sequence>
         *                   <element name="Traslado" maxOccurs="unbounded">
         *                     <complexType>
         *                       <complexContent>
         *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           <attribute name="Impuesto" use="required">
         *                             <simpleType>
         *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                 <whiteSpace value="collapse"/>
         *                                 <enumeration value="IVA"/>
         *                                 <enumeration value="IEPS"/>
         *                               </restriction>
         *                             </simpleType>
         *                           </attribute>
         *                           <attribute name="TasaoCuota" use="required">
         *                             <simpleType>
         *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *                                 <fractionDigits value="6"/>
         *                                 <whiteSpace value="collapse"/>
         *                               </restriction>
         *                             </simpleType>
         *                           </attribute>
         *                           <attribute name="Importe" use="required">
         *                             <simpleType>
         *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *                                 <fractionDigits value="2"/>
         *                                 <whiteSpace value="collapse"/>
         *                                 <minInclusive value="0.01"/>
         *                                 <pattern value="[0-9]{1,14}(.([0-9]{1,2}))"/>
         *                               </restriction>
         *                             </simpleType>
         *                           </attribute>
         *                         </restriction>
         *                       </complexContent>
         *                     </complexType>
         *                   </element>
         *                 </sequence>
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *       </sequence>
         *       <attribute name="Identificador" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <minLength value="1"/>
         *             <whiteSpace value="collapse"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Fecha" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
         *             <whiteSpace value="collapse"/>
         *             <minInclusive value="2015-01-01T00:00:00"/>
         *             <pattern value="([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Rfc" use="required" type="{http://www.sat.gob.mx/EstadoDeCuentaCombustible}t_RFC" />
         *       <attribute name="ClaveEstacion" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <whiteSpace value="collapse"/>
         *             <minLength value="1"/>
         *             <maxLength value="10"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="TAR" type="{http://www.sat.gob.mx/EstadoDeCuentaCombustible}c_TAR" />
         *       <attribute name="Cantidad" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             <minInclusive value="0.001"/>
         *             <fractionDigits value="3"/>
         *             <whiteSpace value="collapse"/>
         *             <pattern value="[0-9]{1,14}(.([0-9]{1,3}))"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="NoIdentificacion" use="required" type="{http://www.sat.gob.mx/EstadoDeCuentaCombustible}c_claveProducto" />
         *       <attribute name="Unidad">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <whiteSpace value="collapse"/>
         *             <minLength value="1"/>
         *             <maxLength value="25"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="NombreCombustible" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <whiteSpace value="collapse"/>
         *             <minLength value="1"/>
         *             <maxLength value="300"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="FolioOperacion" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <whiteSpace value="collapse"/>
         *             <minLength value="1"/>
         *             <maxLength value="50"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="ValorUnitario" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             <minInclusive value="0.001"/>
         *             <fractionDigits value="3"/>
         *             <whiteSpace value="collapse"/>
         *             <pattern value="[0-9]{1,14}(.([0-9]{1,3}))"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Importe" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             <fractionDigits value="2"/>
         *             <whiteSpace value="collapse"/>
         *             <pattern value="[0-9]{1,14}(.([0-9]{1,2}))"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "traslados"
        })
        public static class ConceptoEstadoDeCuentaCombustible
            implements Serializable
        {

            private static final long serialVersionUID = 1L;
            @XmlElement(name = "Traslados", required = true)
            protected EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados traslados;
            @XmlAttribute(name = "Identificador", required = true)
            protected String identificador;
            @XmlAttribute(name = "Fecha", required = true)
            protected XMLGregorianCalendar fecha;
            @XmlAttribute(name = "Rfc", required = true)
            protected String rfc;
            @XmlAttribute(name = "ClaveEstacion", required = true)
            protected String claveEstacion;
            @XmlAttribute(name = "TAR")
            protected String tar;
            @XmlAttribute(name = "Cantidad", required = true)
            protected BigDecimal cantidad;
            @XmlAttribute(name = "NoIdentificacion", required = true)
            protected String noIdentificacion;
            @XmlAttribute(name = "Unidad")
            protected String unidad;
            @XmlAttribute(name = "NombreCombustible", required = true)
            protected String nombreCombustible;
            @XmlAttribute(name = "FolioOperacion", required = true)
            protected String folioOperacion;
            @XmlAttribute(name = "ValorUnitario", required = true)
            protected BigDecimal valorUnitario;
            @XmlAttribute(name = "Importe", required = true)
            protected BigDecimal importe;

            /**
             * Gets the value of the traslados property.
             * 
             * @return
             *     possible object is
             *     {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados }
             *     
             */
            public EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados getTraslados() {
                return traslados;
            }

            /**
             * Sets the value of the traslados property.
             * 
             * @param value
             *     allowed object is
             *     {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados }
             *     
             */
            public void setTraslados(EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados value) {
                this.traslados = value;
            }

            /**
             * Gets the value of the identificador property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdentificador() {
                return identificador;
            }

            /**
             * Sets the value of the identificador property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdentificador(String value) {
                this.identificador = value;
            }

            /**
             * Gets the value of the fecha property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFecha(XMLGregorianCalendar value) {
                this.fecha = value;
            }

            /**
             * Gets the value of the rfc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRfc() {
                return rfc;
            }

            /**
             * Sets the value of the rfc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRfc(String value) {
                this.rfc = value;
            }

            /**
             * Gets the value of the claveEstacion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClaveEstacion() {
                return claveEstacion;
            }

            /**
             * Sets the value of the claveEstacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClaveEstacion(String value) {
                this.claveEstacion = value;
            }

            /**
             * Gets the value of the tar property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTAR() {
                return tar;
            }

            /**
             * Sets the value of the tar property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTAR(String value) {
                this.tar = value;
            }

            /**
             * Gets the value of the cantidad property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getCantidad() {
                return cantidad;
            }

            /**
             * Sets the value of the cantidad property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setCantidad(BigDecimal value) {
                this.cantidad = value;
            }

            /**
             * Gets the value of the noIdentificacion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoIdentificacion() {
                return noIdentificacion;
            }

            /**
             * Sets the value of the noIdentificacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoIdentificacion(String value) {
                this.noIdentificacion = value;
            }

            /**
             * Gets the value of the unidad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnidad() {
                return unidad;
            }

            /**
             * Sets the value of the unidad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnidad(String value) {
                this.unidad = value;
            }

            /**
             * Gets the value of the nombreCombustible property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNombreCombustible() {
                return nombreCombustible;
            }

            /**
             * Sets the value of the nombreCombustible property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNombreCombustible(String value) {
                this.nombreCombustible = value;
            }

            /**
             * Gets the value of the folioOperacion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFolioOperacion() {
                return folioOperacion;
            }

            /**
             * Sets the value of the folioOperacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFolioOperacion(String value) {
                this.folioOperacion = value;
            }

            /**
             * Gets the value of the valorUnitario property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValorUnitario() {
                return valorUnitario;
            }

            /**
             * Sets the value of the valorUnitario property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValorUnitario(BigDecimal value) {
                this.valorUnitario = value;
            }

            /**
             * Gets the value of the importe property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImporte() {
                return importe;
            }

            /**
             * Sets the value of the importe property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImporte(BigDecimal value) {
                this.importe = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       <sequence>
             *         <element name="Traslado" maxOccurs="unbounded">
             *           <complexType>
             *             <complexContent>
             *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 <attribute name="Impuesto" use="required">
             *                   <simpleType>
             *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                       <whiteSpace value="collapse"/>
             *                       <enumeration value="IVA"/>
             *                       <enumeration value="IEPS"/>
             *                     </restriction>
             *                   </simpleType>
             *                 </attribute>
             *                 <attribute name="TasaoCuota" use="required">
             *                   <simpleType>
             *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
             *                       <fractionDigits value="6"/>
             *                       <whiteSpace value="collapse"/>
             *                     </restriction>
             *                   </simpleType>
             *                 </attribute>
             *                 <attribute name="Importe" use="required">
             *                   <simpleType>
             *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
             *                       <fractionDigits value="2"/>
             *                       <whiteSpace value="collapse"/>
             *                       <minInclusive value="0.01"/>
             *                       <pattern value="[0-9]{1,14}(.([0-9]{1,2}))"/>
             *                     </restriction>
             *                   </simpleType>
             *                 </attribute>
             *               </restriction>
             *             </complexContent>
             *           </complexType>
             *         </element>
             *       </sequence>
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "traslado"
            })
            public static class Traslados
                implements Serializable
            {

                private static final long serialVersionUID = 1L;
                @XmlElement(name = "Traslado", required = true)
                protected List<EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados.Traslado> traslado;

                /**
                 * Gets the value of the traslado property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a {@code set} method for the traslado property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTraslado().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados.Traslado }
                 * 
                 * 
                 * @return
                 *     The value of the traslado property.
                 */
                public List<EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados.Traslado> getTraslado() {
                    if (traslado == null) {
                        traslado = new ArrayList<>();
                    }
                    return this.traslado;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>{@code
                 * <complexType>
                 *   <complexContent>
                 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       <attribute name="Impuesto" use="required">
                 *         <simpleType>
                 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *             <whiteSpace value="collapse"/>
                 *             <enumeration value="IVA"/>
                 *             <enumeration value="IEPS"/>
                 *           </restriction>
                 *         </simpleType>
                 *       </attribute>
                 *       <attribute name="TasaoCuota" use="required">
                 *         <simpleType>
                 *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
                 *             <fractionDigits value="6"/>
                 *             <whiteSpace value="collapse"/>
                 *           </restriction>
                 *         </simpleType>
                 *       </attribute>
                 *       <attribute name="Importe" use="required">
                 *         <simpleType>
                 *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
                 *             <fractionDigits value="2"/>
                 *             <whiteSpace value="collapse"/>
                 *             <minInclusive value="0.01"/>
                 *             <pattern value="[0-9]{1,14}(.([0-9]{1,2}))"/>
                 *           </restriction>
                 *         </simpleType>
                 *       </attribute>
                 *     </restriction>
                 *   </complexContent>
                 * </complexType>
                 * }</pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Traslado
                    implements Serializable
                {

                    private static final long serialVersionUID = 1L;
                    @XmlAttribute(name = "Impuesto", required = true)
                    protected String impuesto;
                    @XmlAttribute(name = "TasaoCuota", required = true)
                    protected BigDecimal tasaoCuota;
                    @XmlAttribute(name = "Importe", required = true)
                    protected BigDecimal importe;

                    /**
                     * Gets the value of the impuesto property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getImpuesto() {
                        return impuesto;
                    }

                    /**
                     * Sets the value of the impuesto property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setImpuesto(String value) {
                        this.impuesto = value;
                    }

                    /**
                     * Gets the value of the tasaoCuota property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getTasaoCuota() {
                        return tasaoCuota;
                    }

                    /**
                     * Sets the value of the tasaoCuota property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setTasaoCuota(BigDecimal value) {
                        this.tasaoCuota = value;
                    }

                    /**
                     * Gets the value of the importe property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getImporte() {
                        return importe;
                    }

                    /**
                     * Sets the value of the importe property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setImporte(BigDecimal value) {
                        this.importe = value;
                    }

                }

            }

        }

    }

}
