//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.gob.sat.cfdi.nomina11;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Percepciones" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Percepcion" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <attribute name="TipoPercepcion" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                 <minInclusive value="1"/>
 *                                 <pattern value="[0-9]{3}"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Clave" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <minLength value="3"/>
 *                                 <maxLength value="15"/>
 *                                 <whiteSpace value="collapse"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Concepto" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <minLength value="1"/>
 *                                 <maxLength value="100"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                           <attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *                 <attribute name="TotalGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                 <attribute name="TotalExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="Deducciones" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Deduccion" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <attribute name="TipoDeduccion" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                 <minInclusive value="1"/>
 *                                 <pattern value="[0-9]{3}"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Clave" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <minLength value="3"/>
 *                                 <maxLength value="15"/>
 *                                 <whiteSpace value="collapse"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Concepto" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <minLength value="1"/>
 *                                 <maxLength value="100"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                           <attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *                 <attribute name="TotalGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                 <attribute name="TotalExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="Incapacidades" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Incapacidad" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <attribute name="DiasIncapacidad" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 <fractionDigits value="6"/>
 *                                 <minInclusive value="1"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="TipoIncapacidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           <attribute name="Descuento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="HorasExtras" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="HorasExtra" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <attribute name="Dias" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           <attribute name="TipoHoras" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <whiteSpace value="collapse"/>
 *                                 <enumeration value="Dobles"/>
 *                                 <enumeration value="Triples"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="HorasExtra" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           <attribute name="ImportePagado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.1" />
 *       <attribute name="RegistroPatronal">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="20"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="NumEmpleado" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="15"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="CURP" use="required" type="{http://www.sat.gob.mx/nomina}t_CURP" />
 *       <attribute name="TipoRegimen" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             <minInclusive value="1"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="NumSeguridadSocial">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="15"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="FechaPago" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       <attribute name="FechaInicialPago" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       <attribute name="FechaFinalPago" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       <attribute name="NumDiasPagados" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             <fractionDigits value="6"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="Departamento">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="100"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="CLABE" type="{http://www.sat.gob.mx/nomina}t_Clabe" />
 *       <attribute name="Banco">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             <minInclusive value="1"/>
 *             <pattern value="[0-9]{3}"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="FechaInicioRelLaboral" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       <attribute name="Antiguedad" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       <attribute name="Puesto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="TipoContrato" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="TipoJornada" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="PeriodicidadPago" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="100"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="SalarioBaseCotApor" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *       <attribute name="RiesgoPuesto">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             <minInclusive value="1"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="SalarioDiarioIntegrado" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "percepciones",
    "deducciones",
    "incapacidades",
    "horasExtras"
})
@XmlRootElement(name = "Nomina")
public class Nomina
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "Percepciones")
    protected Nomina.Percepciones percepciones;
    @XmlElement(name = "Deducciones")
    protected Nomina.Deducciones deducciones;
    @XmlElement(name = "Incapacidades")
    protected Nomina.Incapacidades incapacidades;
    @XmlElement(name = "HorasExtras")
    protected Nomina.HorasExtras horasExtras;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "RegistroPatronal")
    protected String registroPatronal;
    @XmlAttribute(name = "NumEmpleado", required = true)
    protected String numEmpleado;
    @XmlAttribute(name = "CURP", required = true)
    protected String curp;
    @XmlAttribute(name = "TipoRegimen", required = true)
    protected int tipoRegimen;
    @XmlAttribute(name = "NumSeguridadSocial")
    protected String numSeguridadSocial;
    @XmlAttribute(name = "FechaPago", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaPago;
    @XmlAttribute(name = "FechaInicialPago", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaInicialPago;
    @XmlAttribute(name = "FechaFinalPago", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaFinalPago;
    @XmlAttribute(name = "NumDiasPagados", required = true)
    protected BigDecimal numDiasPagados;
    @XmlAttribute(name = "Departamento")
    protected String departamento;
    @XmlAttribute(name = "CLABE")
    protected BigInteger clabe;
    @XmlAttribute(name = "Banco")
    protected Integer banco;
    @XmlAttribute(name = "FechaInicioRelLaboral")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaInicioRelLaboral;
    @XmlAttribute(name = "Antiguedad")
    protected Integer antiguedad;
    @XmlAttribute(name = "Puesto")
    protected String puesto;
    @XmlAttribute(name = "TipoContrato")
    protected String tipoContrato;
    @XmlAttribute(name = "TipoJornada")
    protected String tipoJornada;
    @XmlAttribute(name = "PeriodicidadPago", required = true)
    protected String periodicidadPago;
    @XmlAttribute(name = "SalarioBaseCotApor")
    protected BigDecimal salarioBaseCotApor;
    @XmlAttribute(name = "RiesgoPuesto")
    protected Integer riesgoPuesto;
    @XmlAttribute(name = "SalarioDiarioIntegrado")
    protected BigDecimal salarioDiarioIntegrado;

    /**
     * Gets the value of the percepciones property.
     * 
     * @return
     *     possible object is
     *     {@link Nomina.Percepciones }
     *     
     */
    public Nomina.Percepciones getPercepciones() {
        return percepciones;
    }

    /**
     * Sets the value of the percepciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nomina.Percepciones }
     *     
     */
    public void setPercepciones(Nomina.Percepciones value) {
        this.percepciones = value;
    }

    /**
     * Gets the value of the deducciones property.
     * 
     * @return
     *     possible object is
     *     {@link Nomina.Deducciones }
     *     
     */
    public Nomina.Deducciones getDeducciones() {
        return deducciones;
    }

    /**
     * Sets the value of the deducciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nomina.Deducciones }
     *     
     */
    public void setDeducciones(Nomina.Deducciones value) {
        this.deducciones = value;
    }

    /**
     * Gets the value of the incapacidades property.
     * 
     * @return
     *     possible object is
     *     {@link Nomina.Incapacidades }
     *     
     */
    public Nomina.Incapacidades getIncapacidades() {
        return incapacidades;
    }

    /**
     * Sets the value of the incapacidades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nomina.Incapacidades }
     *     
     */
    public void setIncapacidades(Nomina.Incapacidades value) {
        this.incapacidades = value;
    }

    /**
     * Gets the value of the horasExtras property.
     * 
     * @return
     *     possible object is
     *     {@link Nomina.HorasExtras }
     *     
     */
    public Nomina.HorasExtras getHorasExtras() {
        return horasExtras;
    }

    /**
     * Sets the value of the horasExtras property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nomina.HorasExtras }
     *     
     */
    public void setHorasExtras(Nomina.HorasExtras value) {
        this.horasExtras = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.1";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the registroPatronal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistroPatronal() {
        return registroPatronal;
    }

    /**
     * Sets the value of the registroPatronal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistroPatronal(String value) {
        this.registroPatronal = value;
    }

    /**
     * Gets the value of the numEmpleado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumEmpleado() {
        return numEmpleado;
    }

    /**
     * Sets the value of the numEmpleado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumEmpleado(String value) {
        this.numEmpleado = value;
    }

    /**
     * Gets the value of the curp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURP() {
        return curp;
    }

    /**
     * Sets the value of the curp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURP(String value) {
        this.curp = value;
    }

    /**
     * Gets the value of the tipoRegimen property.
     * 
     */
    public int getTipoRegimen() {
        return tipoRegimen;
    }

    /**
     * Sets the value of the tipoRegimen property.
     * 
     */
    public void setTipoRegimen(int value) {
        this.tipoRegimen = value;
    }

    /**
     * Gets the value of the numSeguridadSocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumSeguridadSocial() {
        return numSeguridadSocial;
    }

    /**
     * Sets the value of the numSeguridadSocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumSeguridadSocial(String value) {
        this.numSeguridadSocial = value;
    }

    /**
     * Gets the value of the fechaPago property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaPago() {
        return fechaPago;
    }

    /**
     * Sets the value of the fechaPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaPago(XMLGregorianCalendar value) {
        this.fechaPago = value;
    }

    /**
     * Gets the value of the fechaInicialPago property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaInicialPago() {
        return fechaInicialPago;
    }

    /**
     * Sets the value of the fechaInicialPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaInicialPago(XMLGregorianCalendar value) {
        this.fechaInicialPago = value;
    }

    /**
     * Gets the value of the fechaFinalPago property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaFinalPago() {
        return fechaFinalPago;
    }

    /**
     * Sets the value of the fechaFinalPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaFinalPago(XMLGregorianCalendar value) {
        this.fechaFinalPago = value;
    }

    /**
     * Gets the value of the numDiasPagados property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumDiasPagados() {
        return numDiasPagados;
    }

    /**
     * Sets the value of the numDiasPagados property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumDiasPagados(BigDecimal value) {
        this.numDiasPagados = value;
    }

    /**
     * Gets the value of the departamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartamento() {
        return departamento;
    }

    /**
     * Sets the value of the departamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartamento(String value) {
        this.departamento = value;
    }

    /**
     * Gets the value of the clabe property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCLABE() {
        return clabe;
    }

    /**
     * Sets the value of the clabe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCLABE(BigInteger value) {
        this.clabe = value;
    }

    /**
     * Gets the value of the banco property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBanco() {
        return banco;
    }

    /**
     * Sets the value of the banco property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBanco(Integer value) {
        this.banco = value;
    }

    /**
     * Gets the value of the fechaInicioRelLaboral property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaInicioRelLaboral() {
        return fechaInicioRelLaboral;
    }

    /**
     * Sets the value of the fechaInicioRelLaboral property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaInicioRelLaboral(XMLGregorianCalendar value) {
        this.fechaInicioRelLaboral = value;
    }

    /**
     * Gets the value of the antiguedad property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAntiguedad() {
        return antiguedad;
    }

    /**
     * Sets the value of the antiguedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAntiguedad(Integer value) {
        this.antiguedad = value;
    }

    /**
     * Gets the value of the puesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPuesto() {
        return puesto;
    }

    /**
     * Sets the value of the puesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPuesto(String value) {
        this.puesto = value;
    }

    /**
     * Gets the value of the tipoContrato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoContrato() {
        return tipoContrato;
    }

    /**
     * Sets the value of the tipoContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoContrato(String value) {
        this.tipoContrato = value;
    }

    /**
     * Gets the value of the tipoJornada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoJornada() {
        return tipoJornada;
    }

    /**
     * Sets the value of the tipoJornada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoJornada(String value) {
        this.tipoJornada = value;
    }

    /**
     * Gets the value of the periodicidadPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodicidadPago() {
        return periodicidadPago;
    }

    /**
     * Sets the value of the periodicidadPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodicidadPago(String value) {
        this.periodicidadPago = value;
    }

    /**
     * Gets the value of the salarioBaseCotApor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSalarioBaseCotApor() {
        return salarioBaseCotApor;
    }

    /**
     * Sets the value of the salarioBaseCotApor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSalarioBaseCotApor(BigDecimal value) {
        this.salarioBaseCotApor = value;
    }

    /**
     * Gets the value of the riesgoPuesto property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRiesgoPuesto() {
        return riesgoPuesto;
    }

    /**
     * Sets the value of the riesgoPuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRiesgoPuesto(Integer value) {
        this.riesgoPuesto = value;
    }

    /**
     * Gets the value of the salarioDiarioIntegrado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSalarioDiarioIntegrado() {
        return salarioDiarioIntegrado;
    }

    /**
     * Sets the value of the salarioDiarioIntegrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSalarioDiarioIntegrado(BigDecimal value) {
        this.salarioDiarioIntegrado = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Deduccion" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <attribute name="TipoDeduccion" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       <minInclusive value="1"/>
     *                       <pattern value="[0-9]{3}"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Clave" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <minLength value="3"/>
     *                       <maxLength value="15"/>
     *                       <whiteSpace value="collapse"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Concepto" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <minLength value="1"/>
     *                       <maxLength value="100"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *                 <attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *       <attribute name="TotalGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *       <attribute name="TotalExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deduccion"
    })
    public static class Deducciones
        implements Serializable
    {

        private static final long serialVersionUID = 1L;
        @XmlElement(name = "Deduccion", required = true)
        protected List<Nomina.Deducciones.Deduccion> deduccion;
        @XmlAttribute(name = "TotalGravado", required = true)
        protected BigDecimal totalGravado;
        @XmlAttribute(name = "TotalExento", required = true)
        protected BigDecimal totalExento;

        /**
         * Gets the value of the deduccion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the deduccion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeduccion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nomina.Deducciones.Deduccion }
         * 
         * 
         * @return
         *     The value of the deduccion property.
         */
        public List<Nomina.Deducciones.Deduccion> getDeduccion() {
            if (deduccion == null) {
                deduccion = new ArrayList<>();
            }
            return this.deduccion;
        }

        /**
         * Gets the value of the totalGravado property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalGravado() {
            return totalGravado;
        }

        /**
         * Sets the value of the totalGravado property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotalGravado(BigDecimal value) {
            this.totalGravado = value;
        }

        /**
         * Gets the value of the totalExento property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalExento() {
            return totalExento;
        }

        /**
         * Sets the value of the totalExento property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotalExento(BigDecimal value) {
            this.totalExento = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <attribute name="TipoDeduccion" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             <minInclusive value="1"/>
         *             <pattern value="[0-9]{3}"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Clave" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <minLength value="3"/>
         *             <maxLength value="15"/>
         *             <whiteSpace value="collapse"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Concepto" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <minLength value="1"/>
         *             <maxLength value="100"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *       <attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Deduccion
            implements Serializable
        {

            private static final long serialVersionUID = 1L;
            @XmlAttribute(name = "TipoDeduccion", required = true)
            protected int tipoDeduccion;
            @XmlAttribute(name = "Clave", required = true)
            protected String clave;
            @XmlAttribute(name = "Concepto", required = true)
            protected String concepto;
            @XmlAttribute(name = "ImporteGravado", required = true)
            protected BigDecimal importeGravado;
            @XmlAttribute(name = "ImporteExento", required = true)
            protected BigDecimal importeExento;

            /**
             * Gets the value of the tipoDeduccion property.
             * 
             */
            public int getTipoDeduccion() {
                return tipoDeduccion;
            }

            /**
             * Sets the value of the tipoDeduccion property.
             * 
             */
            public void setTipoDeduccion(int value) {
                this.tipoDeduccion = value;
            }

            /**
             * Gets the value of the clave property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClave() {
                return clave;
            }

            /**
             * Sets the value of the clave property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClave(String value) {
                this.clave = value;
            }

            /**
             * Gets the value of the concepto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getConcepto() {
                return concepto;
            }

            /**
             * Sets the value of the concepto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConcepto(String value) {
                this.concepto = value;
            }

            /**
             * Gets the value of the importeGravado property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImporteGravado() {
                return importeGravado;
            }

            /**
             * Sets the value of the importeGravado property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImporteGravado(BigDecimal value) {
                this.importeGravado = value;
            }

            /**
             * Gets the value of the importeExento property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImporteExento() {
                return importeExento;
            }

            /**
             * Sets the value of the importeExento property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImporteExento(BigDecimal value) {
                this.importeExento = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="HorasExtra" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <attribute name="Dias" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 <attribute name="TipoHoras" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <whiteSpace value="collapse"/>
     *                       <enumeration value="Dobles"/>
     *                       <enumeration value="Triples"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="HorasExtra" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 <attribute name="ImportePagado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "horasExtra"
    })
    public static class HorasExtras
        implements Serializable
    {

        private static final long serialVersionUID = 1L;
        @XmlElement(name = "HorasExtra", required = true)
        protected List<Nomina.HorasExtras.HorasExtra> horasExtra;

        /**
         * Gets the value of the horasExtra property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the horasExtra property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHorasExtra().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nomina.HorasExtras.HorasExtra }
         * 
         * 
         * @return
         *     The value of the horasExtra property.
         */
        public List<Nomina.HorasExtras.HorasExtra> getHorasExtra() {
            if (horasExtra == null) {
                horasExtra = new ArrayList<>();
            }
            return this.horasExtra;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <attribute name="Dias" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       <attribute name="TipoHoras" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <whiteSpace value="collapse"/>
         *             <enumeration value="Dobles"/>
         *             <enumeration value="Triples"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="HorasExtra" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       <attribute name="ImportePagado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class HorasExtra
            implements Serializable
        {

            private static final long serialVersionUID = 1L;
            @XmlAttribute(name = "Dias", required = true)
            protected int dias;
            @XmlAttribute(name = "TipoHoras", required = true)
            protected String tipoHoras;
            @XmlAttribute(name = "HorasExtra", required = true)
            protected int horasExtra;
            @XmlAttribute(name = "ImportePagado", required = true)
            protected BigDecimal importePagado;

            /**
             * Gets the value of the dias property.
             * 
             */
            public int getDias() {
                return dias;
            }

            /**
             * Sets the value of the dias property.
             * 
             */
            public void setDias(int value) {
                this.dias = value;
            }

            /**
             * Gets the value of the tipoHoras property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoHoras() {
                return tipoHoras;
            }

            /**
             * Sets the value of the tipoHoras property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoHoras(String value) {
                this.tipoHoras = value;
            }

            /**
             * Gets the value of the horasExtra property.
             * 
             */
            public int getHorasExtra() {
                return horasExtra;
            }

            /**
             * Sets the value of the horasExtra property.
             * 
             */
            public void setHorasExtra(int value) {
                this.horasExtra = value;
            }

            /**
             * Gets the value of the importePagado property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImportePagado() {
                return importePagado;
            }

            /**
             * Sets the value of the importePagado property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImportePagado(BigDecimal value) {
                this.importePagado = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Incapacidad" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <attribute name="DiasIncapacidad" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       <fractionDigits value="6"/>
     *                       <minInclusive value="1"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="TipoIncapacidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 <attribute name="Descuento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "incapacidad"
    })
    public static class Incapacidades
        implements Serializable
    {

        private static final long serialVersionUID = 1L;
        @XmlElement(name = "Incapacidad", required = true)
        protected List<Nomina.Incapacidades.Incapacidad> incapacidad;

        /**
         * Gets the value of the incapacidad property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the incapacidad property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIncapacidad().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nomina.Incapacidades.Incapacidad }
         * 
         * 
         * @return
         *     The value of the incapacidad property.
         */
        public List<Nomina.Incapacidades.Incapacidad> getIncapacidad() {
            if (incapacidad == null) {
                incapacidad = new ArrayList<>();
            }
            return this.incapacidad;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <attribute name="DiasIncapacidad" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             <fractionDigits value="6"/>
         *             <minInclusive value="1"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="TipoIncapacidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       <attribute name="Descuento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Incapacidad
            implements Serializable
        {

            private static final long serialVersionUID = 1L;
            @XmlAttribute(name = "DiasIncapacidad", required = true)
            protected BigDecimal diasIncapacidad;
            @XmlAttribute(name = "TipoIncapacidad", required = true)
            protected int tipoIncapacidad;
            @XmlAttribute(name = "Descuento", required = true)
            protected BigDecimal descuento;

            /**
             * Gets the value of the diasIncapacidad property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiasIncapacidad() {
                return diasIncapacidad;
            }

            /**
             * Sets the value of the diasIncapacidad property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiasIncapacidad(BigDecimal value) {
                this.diasIncapacidad = value;
            }

            /**
             * Gets the value of the tipoIncapacidad property.
             * 
             */
            public int getTipoIncapacidad() {
                return tipoIncapacidad;
            }

            /**
             * Sets the value of the tipoIncapacidad property.
             * 
             */
            public void setTipoIncapacidad(int value) {
                this.tipoIncapacidad = value;
            }

            /**
             * Gets the value of the descuento property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDescuento() {
                return descuento;
            }

            /**
             * Sets the value of the descuento property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDescuento(BigDecimal value) {
                this.descuento = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Percepcion" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <attribute name="TipoPercepcion" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       <minInclusive value="1"/>
     *                       <pattern value="[0-9]{3}"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Clave" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <minLength value="3"/>
     *                       <maxLength value="15"/>
     *                       <whiteSpace value="collapse"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Concepto" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <minLength value="1"/>
     *                       <maxLength value="100"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *                 <attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *       <attribute name="TotalGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *       <attribute name="TotalExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "percepcion"
    })
    public static class Percepciones
        implements Serializable
    {

        private static final long serialVersionUID = 1L;
        @XmlElement(name = "Percepcion", required = true)
        protected List<Nomina.Percepciones.Percepcion> percepcion;
        @XmlAttribute(name = "TotalGravado", required = true)
        protected BigDecimal totalGravado;
        @XmlAttribute(name = "TotalExento", required = true)
        protected BigDecimal totalExento;

        /**
         * Gets the value of the percepcion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the percepcion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPercepcion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nomina.Percepciones.Percepcion }
         * 
         * 
         * @return
         *     The value of the percepcion property.
         */
        public List<Nomina.Percepciones.Percepcion> getPercepcion() {
            if (percepcion == null) {
                percepcion = new ArrayList<>();
            }
            return this.percepcion;
        }

        /**
         * Gets the value of the totalGravado property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalGravado() {
            return totalGravado;
        }

        /**
         * Sets the value of the totalGravado property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotalGravado(BigDecimal value) {
            this.totalGravado = value;
        }

        /**
         * Gets the value of the totalExento property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalExento() {
            return totalExento;
        }

        /**
         * Sets the value of the totalExento property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotalExento(BigDecimal value) {
            this.totalExento = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <attribute name="TipoPercepcion" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             <minInclusive value="1"/>
         *             <pattern value="[0-9]{3}"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Clave" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <minLength value="3"/>
         *             <maxLength value="15"/>
         *             <whiteSpace value="collapse"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Concepto" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <minLength value="1"/>
         *             <maxLength value="100"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *       <attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Percepcion
            implements Serializable
        {

            private static final long serialVersionUID = 1L;
            @XmlAttribute(name = "TipoPercepcion", required = true)
            protected int tipoPercepcion;
            @XmlAttribute(name = "Clave", required = true)
            protected String clave;
            @XmlAttribute(name = "Concepto", required = true)
            protected String concepto;
            @XmlAttribute(name = "ImporteGravado", required = true)
            protected BigDecimal importeGravado;
            @XmlAttribute(name = "ImporteExento", required = true)
            protected BigDecimal importeExento;

            /**
             * Gets the value of the tipoPercepcion property.
             * 
             */
            public int getTipoPercepcion() {
                return tipoPercepcion;
            }

            /**
             * Sets the value of the tipoPercepcion property.
             * 
             */
            public void setTipoPercepcion(int value) {
                this.tipoPercepcion = value;
            }

            /**
             * Gets the value of the clave property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClave() {
                return clave;
            }

            /**
             * Sets the value of the clave property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClave(String value) {
                this.clave = value;
            }

            /**
             * Gets the value of the concepto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getConcepto() {
                return concepto;
            }

            /**
             * Sets the value of the concepto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConcepto(String value) {
                this.concepto = value;
            }

            /**
             * Gets the value of the importeGravado property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImporteGravado() {
                return importeGravado;
            }

            /**
             * Sets the value of the importeGravado property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImporteGravado(BigDecimal value) {
                this.importeGravado = value;
            }

            /**
             * Gets the value of the importeExento property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImporteExento() {
                return importeExento;
            }

            /**
             * Sets the value of the importeExento property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImporteExento(BigDecimal value) {
                this.importeExento = value;
            }

        }

    }

}
