//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.gob.sat.cfdi.GastosHidrocarburos10;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Erogacion" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="DocumentoRelacionado" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <attribute name="OrigenErogacion" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <enumeration value="Nacional"/>
 *                                 <enumeration value="Extranjero"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="FolioFiscalVinculado">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <length value="36"/>
 *                                 <whiteSpace value="collapse"/>
 *                                 <pattern value="[a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="RFCProveedor">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <minLength value="12"/>
 *                                 <maxLength value="13"/>
 *                                 <whiteSpace value="collapse"/>
 *                                 <pattern value="[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="MontoTotalIVA" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
 *                           <attribute name="MontoRetencionISR" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
 *                           <attribute name="MontoRetencionIVA" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
 *                           <attribute name="MontoRetencionOtrosImpuestos" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
 *                           <attribute name="NumeroPedimentoVinculado">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <length value="21"/>
 *                                 <pattern value="[0-9]{2}  [0-9]{2}  [0-9]{4}  [0-9]{7}"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="ClavePedimentoVinculado" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}ClavePedimento" />
 *                           <attribute name="ClavePagoPedimentoVinculado" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}ClavePagoPedimento" />
 *                           <attribute name="MontoIVAPedimento" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
 *                           <attribute name="OtrosImpuestosPagadosPedimento" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
 *                           <attribute name="FechaFolioFiscalVinculado">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                                 <whiteSpace value="collapse"/>
 *                                 <pattern value="([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Mes" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Meses" />
 *                           <attribute name="MontoTotalErogaciones" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="Actividades" maxOccurs="unbounded" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="SubActividades" maxOccurs="unbounded" minOccurs="0">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     <sequence>
 *                                       <element name="Tareas" maxOccurs="unbounded" minOccurs="0">
 *                                         <complexType>
 *                                           <complexContent>
 *                                             <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               <attribute name="TareaRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Tareas" />
 *                                             </restriction>
 *                                           </complexContent>
 *                                         </complexType>
 *                                       </element>
 *                                     </sequence>
 *                                     <attribute name="SubActividadRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}SubActividad" />
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                           </sequence>
 *                           <attribute name="ActividadRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Actividades" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="CentroCostos" maxOccurs="unbounded" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="Yacimientos" maxOccurs="unbounded" minOccurs="0">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     <sequence>
 *                                       <element name="Pozos" maxOccurs="unbounded" minOccurs="0">
 *                                         <complexType>
 *                                           <complexContent>
 *                                             <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               <attribute name="Pozo">
 *                                                 <simpleType>
 *                                                   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                     <minLength value="1"/>
 *                                                     <maxLength value="50"/>
 *                                                     <whiteSpace value="collapse"/>
 *                                                     <pattern value="[^|]{1,50}"/>
 *                                                   </restriction>
 *                                                 </simpleType>
 *                                               </attribute>
 *                                             </restriction>
 *                                           </complexContent>
 *                                         </complexType>
 *                                       </element>
 *                                     </sequence>
 *                                     <attribute name="Yacimiento">
 *                                       <simpleType>
 *                                         <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           <minLength value="1"/>
 *                                           <maxLength value="50"/>
 *                                           <whiteSpace value="collapse"/>
 *                                           <pattern value="[^|]{1,50}"/>
 *                                         </restriction>
 *                                       </simpleType>
 *                                     </attribute>
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                           </sequence>
 *                           <attribute name="Campo">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <minLength value="1"/>
 *                                 <maxLength value="50"/>
 *                                 <whiteSpace value="collapse"/>
 *                                 <pattern value="[^|]{1,50}"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *                 <attribute name="TipoErogacion" use="required">
 *                   <simpleType>
 *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       <whiteSpace value="collapse"/>
 *                       <enumeration value="Costo"/>
 *                       <enumeration value="Gasto"/>
 *                       <enumeration value="Inversión"/>
 *                     </restriction>
 *                   </simpleType>
 *                 </attribute>
 *                 <attribute name="MontocuErogacion" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
 *                 <attribute name="Porcentaje" use="required">
 *                   <simpleType>
 *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                       <fractionDigits value="3"/>
 *                       <maxInclusive value="99.999"/>
 *                       <minInclusive value="00.001"/>
 *                       <whiteSpace value="collapse"/>
 *                     </restriction>
 *                   </simpleType>
 *                 </attribute>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attribute name="Version" use="required" fixed="1.0">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="NumeroContrato" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="50"/>
 *             <whiteSpace value="collapse"/>
 *             <pattern value="[^|]{1,50}"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="AreaContractual">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="50"/>
 *             <whiteSpace value="collapse"/>
 *             <pattern value="[^|]{1,50}"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "erogacion"
})
@XmlRootElement(name = "GastosHidrocarburos")
public class GastosHidrocarburos
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "Erogacion", required = true)
    protected List<GastosHidrocarburos.Erogacion> erogacion;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "NumeroContrato", required = true)
    protected String numeroContrato;
    @XmlAttribute(name = "AreaContractual")
    protected String areaContractual;

    /**
     * Gets the value of the erogacion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the erogacion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErogacion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GastosHidrocarburos.Erogacion }
     * 
     * 
     * @return
     *     The value of the erogacion property.
     */
    public List<GastosHidrocarburos.Erogacion> getErogacion() {
        if (erogacion == null) {
            erogacion = new ArrayList<>();
        }
        return this.erogacion;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the numeroContrato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroContrato() {
        return numeroContrato;
    }

    /**
     * Sets the value of the numeroContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroContrato(String value) {
        this.numeroContrato = value;
    }

    /**
     * Gets the value of the areaContractual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaContractual() {
        return areaContractual;
    }

    /**
     * Sets the value of the areaContractual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaContractual(String value) {
        this.areaContractual = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="DocumentoRelacionado" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <attribute name="OrigenErogacion" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <enumeration value="Nacional"/>
     *                       <enumeration value="Extranjero"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="FolioFiscalVinculado">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <length value="36"/>
     *                       <whiteSpace value="collapse"/>
     *                       <pattern value="[a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="RFCProveedor">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <minLength value="12"/>
     *                       <maxLength value="13"/>
     *                       <whiteSpace value="collapse"/>
     *                       <pattern value="[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="MontoTotalIVA" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
     *                 <attribute name="MontoRetencionISR" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
     *                 <attribute name="MontoRetencionIVA" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
     *                 <attribute name="MontoRetencionOtrosImpuestos" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
     *                 <attribute name="NumeroPedimentoVinculado">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <length value="21"/>
     *                       <pattern value="[0-9]{2}  [0-9]{2}  [0-9]{4}  [0-9]{7}"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="ClavePedimentoVinculado" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}ClavePedimento" />
     *                 <attribute name="ClavePagoPedimentoVinculado" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}ClavePagoPedimento" />
     *                 <attribute name="MontoIVAPedimento" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
     *                 <attribute name="OtrosImpuestosPagadosPedimento" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
     *                 <attribute name="FechaFolioFiscalVinculado">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *                       <whiteSpace value="collapse"/>
     *                       <pattern value="([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Mes" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Meses" />
     *                 <attribute name="MontoTotalErogaciones" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="Actividades" maxOccurs="unbounded" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="SubActividades" maxOccurs="unbounded" minOccurs="0">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           <sequence>
     *                             <element name="Tareas" maxOccurs="unbounded" minOccurs="0">
     *                               <complexType>
     *                                 <complexContent>
     *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     <attribute name="TareaRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Tareas" />
     *                                   </restriction>
     *                                 </complexContent>
     *                               </complexType>
     *                             </element>
     *                           </sequence>
     *                           <attribute name="SubActividadRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}SubActividad" />
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                 </sequence>
     *                 <attribute name="ActividadRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Actividades" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="CentroCostos" maxOccurs="unbounded" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="Yacimientos" maxOccurs="unbounded" minOccurs="0">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           <sequence>
     *                             <element name="Pozos" maxOccurs="unbounded" minOccurs="0">
     *                               <complexType>
     *                                 <complexContent>
     *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     <attribute name="Pozo">
     *                                       <simpleType>
     *                                         <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                           <minLength value="1"/>
     *                                           <maxLength value="50"/>
     *                                           <whiteSpace value="collapse"/>
     *                                           <pattern value="[^|]{1,50}"/>
     *                                         </restriction>
     *                                       </simpleType>
     *                                     </attribute>
     *                                   </restriction>
     *                                 </complexContent>
     *                               </complexType>
     *                             </element>
     *                           </sequence>
     *                           <attribute name="Yacimiento">
     *                             <simpleType>
     *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 <minLength value="1"/>
     *                                 <maxLength value="50"/>
     *                                 <whiteSpace value="collapse"/>
     *                                 <pattern value="[^|]{1,50}"/>
     *                               </restriction>
     *                             </simpleType>
     *                           </attribute>
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                 </sequence>
     *                 <attribute name="Campo">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <minLength value="1"/>
     *                       <maxLength value="50"/>
     *                       <whiteSpace value="collapse"/>
     *                       <pattern value="[^|]{1,50}"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *       <attribute name="TipoErogacion" use="required">
     *         <simpleType>
     *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             <whiteSpace value="collapse"/>
     *             <enumeration value="Costo"/>
     *             <enumeration value="Gasto"/>
     *             <enumeration value="Inversión"/>
     *           </restriction>
     *         </simpleType>
     *       </attribute>
     *       <attribute name="MontocuErogacion" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
     *       <attribute name="Porcentaje" use="required">
     *         <simpleType>
     *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *             <fractionDigits value="3"/>
     *             <maxInclusive value="99.999"/>
     *             <minInclusive value="00.001"/>
     *             <whiteSpace value="collapse"/>
     *           </restriction>
     *         </simpleType>
     *       </attribute>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentoRelacionado",
        "actividades",
        "centroCostos"
    })
    public static class Erogacion
        implements Serializable
    {

        private static final long serialVersionUID = 1L;
        @XmlElement(name = "DocumentoRelacionado", required = true)
        protected List<GastosHidrocarburos.Erogacion.DocumentoRelacionado> documentoRelacionado;
        @XmlElement(name = "Actividades")
        protected List<GastosHidrocarburos.Erogacion.Actividades> actividades;
        @XmlElement(name = "CentroCostos")
        protected List<GastosHidrocarburos.Erogacion.CentroCostos> centroCostos;
        @XmlAttribute(name = "TipoErogacion", required = true)
        protected String tipoErogacion;
        @XmlAttribute(name = "MontocuErogacion", required = true)
        protected BigDecimal montocuErogacion;
        @XmlAttribute(name = "Porcentaje", required = true)
        protected BigDecimal porcentaje;

        /**
         * Gets the value of the documentoRelacionado property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the documentoRelacionado property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocumentoRelacionado().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GastosHidrocarburos.Erogacion.DocumentoRelacionado }
         * 
         * 
         * @return
         *     The value of the documentoRelacionado property.
         */
        public List<GastosHidrocarburos.Erogacion.DocumentoRelacionado> getDocumentoRelacionado() {
            if (documentoRelacionado == null) {
                documentoRelacionado = new ArrayList<>();
            }
            return this.documentoRelacionado;
        }

        /**
         * Gets the value of the actividades property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the actividades property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getActividades().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GastosHidrocarburos.Erogacion.Actividades }
         * 
         * 
         * @return
         *     The value of the actividades property.
         */
        public List<GastosHidrocarburos.Erogacion.Actividades> getActividades() {
            if (actividades == null) {
                actividades = new ArrayList<>();
            }
            return this.actividades;
        }

        /**
         * Gets the value of the centroCostos property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the centroCostos property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCentroCostos().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GastosHidrocarburos.Erogacion.CentroCostos }
         * 
         * 
         * @return
         *     The value of the centroCostos property.
         */
        public List<GastosHidrocarburos.Erogacion.CentroCostos> getCentroCostos() {
            if (centroCostos == null) {
                centroCostos = new ArrayList<>();
            }
            return this.centroCostos;
        }

        /**
         * Gets the value of the tipoErogacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoErogacion() {
            return tipoErogacion;
        }

        /**
         * Sets the value of the tipoErogacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoErogacion(String value) {
            this.tipoErogacion = value;
        }

        /**
         * Gets the value of the montocuErogacion property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMontocuErogacion() {
            return montocuErogacion;
        }

        /**
         * Sets the value of the montocuErogacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMontocuErogacion(BigDecimal value) {
            this.montocuErogacion = value;
        }

        /**
         * Gets the value of the porcentaje property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPorcentaje() {
            return porcentaje;
        }

        /**
         * Sets the value of the porcentaje property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPorcentaje(BigDecimal value) {
            this.porcentaje = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="SubActividades" maxOccurs="unbounded" minOccurs="0">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 <sequence>
         *                   <element name="Tareas" maxOccurs="unbounded" minOccurs="0">
         *                     <complexType>
         *                       <complexContent>
         *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           <attribute name="TareaRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Tareas" />
         *                         </restriction>
         *                       </complexContent>
         *                     </complexType>
         *                   </element>
         *                 </sequence>
         *                 <attribute name="SubActividadRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}SubActividad" />
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *       </sequence>
         *       <attribute name="ActividadRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Actividades" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "subActividades"
        })
        public static class Actividades
            implements Serializable
        {

            private static final long serialVersionUID = 1L;
            @XmlElement(name = "SubActividades")
            protected List<GastosHidrocarburos.Erogacion.Actividades.SubActividades> subActividades;
            @XmlAttribute(name = "ActividadRelacionada")
            protected String actividadRelacionada;

            /**
             * Gets the value of the subActividades property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a {@code set} method for the subActividades property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSubActividades().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GastosHidrocarburos.Erogacion.Actividades.SubActividades }
             * 
             * 
             * @return
             *     The value of the subActividades property.
             */
            public List<GastosHidrocarburos.Erogacion.Actividades.SubActividades> getSubActividades() {
                if (subActividades == null) {
                    subActividades = new ArrayList<>();
                }
                return this.subActividades;
            }

            /**
             * Gets the value of the actividadRelacionada property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActividadRelacionada() {
                return actividadRelacionada;
            }

            /**
             * Sets the value of the actividadRelacionada property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActividadRelacionada(String value) {
                this.actividadRelacionada = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       <sequence>
             *         <element name="Tareas" maxOccurs="unbounded" minOccurs="0">
             *           <complexType>
             *             <complexContent>
             *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 <attribute name="TareaRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Tareas" />
             *               </restriction>
             *             </complexContent>
             *           </complexType>
             *         </element>
             *       </sequence>
             *       <attribute name="SubActividadRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}SubActividad" />
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tareas"
            })
            public static class SubActividades
                implements Serializable
            {

                private static final long serialVersionUID = 1L;
                @XmlElement(name = "Tareas")
                protected List<GastosHidrocarburos.Erogacion.Actividades.SubActividades.Tareas> tareas;
                @XmlAttribute(name = "SubActividadRelacionada")
                protected String subActividadRelacionada;

                /**
                 * Gets the value of the tareas property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a {@code set} method for the tareas property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTareas().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link GastosHidrocarburos.Erogacion.Actividades.SubActividades.Tareas }
                 * 
                 * 
                 * @return
                 *     The value of the tareas property.
                 */
                public List<GastosHidrocarburos.Erogacion.Actividades.SubActividades.Tareas> getTareas() {
                    if (tareas == null) {
                        tareas = new ArrayList<>();
                    }
                    return this.tareas;
                }

                /**
                 * Gets the value of the subActividadRelacionada property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSubActividadRelacionada() {
                    return subActividadRelacionada;
                }

                /**
                 * Sets the value of the subActividadRelacionada property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSubActividadRelacionada(String value) {
                    this.subActividadRelacionada = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>{@code
                 * <complexType>
                 *   <complexContent>
                 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       <attribute name="TareaRelacionada" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Tareas" />
                 *     </restriction>
                 *   </complexContent>
                 * </complexType>
                 * }</pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Tareas
                    implements Serializable
                {

                    private static final long serialVersionUID = 1L;
                    @XmlAttribute(name = "TareaRelacionada")
                    protected String tareaRelacionada;

                    /**
                     * Gets the value of the tareaRelacionada property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTareaRelacionada() {
                        return tareaRelacionada;
                    }

                    /**
                     * Sets the value of the tareaRelacionada property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTareaRelacionada(String value) {
                        this.tareaRelacionada = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="Yacimientos" maxOccurs="unbounded" minOccurs="0">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 <sequence>
         *                   <element name="Pozos" maxOccurs="unbounded" minOccurs="0">
         *                     <complexType>
         *                       <complexContent>
         *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           <attribute name="Pozo">
         *                             <simpleType>
         *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                 <minLength value="1"/>
         *                                 <maxLength value="50"/>
         *                                 <whiteSpace value="collapse"/>
         *                                 <pattern value="[^|]{1,50}"/>
         *                               </restriction>
         *                             </simpleType>
         *                           </attribute>
         *                         </restriction>
         *                       </complexContent>
         *                     </complexType>
         *                   </element>
         *                 </sequence>
         *                 <attribute name="Yacimiento">
         *                   <simpleType>
         *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       <minLength value="1"/>
         *                       <maxLength value="50"/>
         *                       <whiteSpace value="collapse"/>
         *                       <pattern value="[^|]{1,50}"/>
         *                     </restriction>
         *                   </simpleType>
         *                 </attribute>
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *       </sequence>
         *       <attribute name="Campo">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <minLength value="1"/>
         *             <maxLength value="50"/>
         *             <whiteSpace value="collapse"/>
         *             <pattern value="[^|]{1,50}"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "yacimientos"
        })
        public static class CentroCostos
            implements Serializable
        {

            private static final long serialVersionUID = 1L;
            @XmlElement(name = "Yacimientos")
            protected List<GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos> yacimientos;
            @XmlAttribute(name = "Campo")
            protected String campo;

            /**
             * Gets the value of the yacimientos property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a {@code set} method for the yacimientos property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getYacimientos().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos }
             * 
             * 
             * @return
             *     The value of the yacimientos property.
             */
            public List<GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos> getYacimientos() {
                if (yacimientos == null) {
                    yacimientos = new ArrayList<>();
                }
                return this.yacimientos;
            }

            /**
             * Gets the value of the campo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCampo() {
                return campo;
            }

            /**
             * Sets the value of the campo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCampo(String value) {
                this.campo = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       <sequence>
             *         <element name="Pozos" maxOccurs="unbounded" minOccurs="0">
             *           <complexType>
             *             <complexContent>
             *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 <attribute name="Pozo">
             *                   <simpleType>
             *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                       <minLength value="1"/>
             *                       <maxLength value="50"/>
             *                       <whiteSpace value="collapse"/>
             *                       <pattern value="[^|]{1,50}"/>
             *                     </restriction>
             *                   </simpleType>
             *                 </attribute>
             *               </restriction>
             *             </complexContent>
             *           </complexType>
             *         </element>
             *       </sequence>
             *       <attribute name="Yacimiento">
             *         <simpleType>
             *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             <minLength value="1"/>
             *             <maxLength value="50"/>
             *             <whiteSpace value="collapse"/>
             *             <pattern value="[^|]{1,50}"/>
             *           </restriction>
             *         </simpleType>
             *       </attribute>
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "pozos"
            })
            public static class Yacimientos
                implements Serializable
            {

                private static final long serialVersionUID = 1L;
                @XmlElement(name = "Pozos")
                protected List<GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos.Pozos> pozos;
                @XmlAttribute(name = "Yacimiento")
                protected String yacimiento;

                /**
                 * Gets the value of the pozos property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a {@code set} method for the pozos property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPozos().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos.Pozos }
                 * 
                 * 
                 * @return
                 *     The value of the pozos property.
                 */
                public List<GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos.Pozos> getPozos() {
                    if (pozos == null) {
                        pozos = new ArrayList<>();
                    }
                    return this.pozos;
                }

                /**
                 * Gets the value of the yacimiento property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getYacimiento() {
                    return yacimiento;
                }

                /**
                 * Sets the value of the yacimiento property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setYacimiento(String value) {
                    this.yacimiento = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>{@code
                 * <complexType>
                 *   <complexContent>
                 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       <attribute name="Pozo">
                 *         <simpleType>
                 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *             <minLength value="1"/>
                 *             <maxLength value="50"/>
                 *             <whiteSpace value="collapse"/>
                 *             <pattern value="[^|]{1,50}"/>
                 *           </restriction>
                 *         </simpleType>
                 *       </attribute>
                 *     </restriction>
                 *   </complexContent>
                 * </complexType>
                 * }</pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Pozos
                    implements Serializable
                {

                    private static final long serialVersionUID = 1L;
                    @XmlAttribute(name = "Pozo")
                    protected String pozo;

                    /**
                     * Gets the value of the pozo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPozo() {
                        return pozo;
                    }

                    /**
                     * Sets the value of the pozo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPozo(String value) {
                        this.pozo = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <attribute name="OrigenErogacion" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <enumeration value="Nacional"/>
         *             <enumeration value="Extranjero"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="FolioFiscalVinculado">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <length value="36"/>
         *             <whiteSpace value="collapse"/>
         *             <pattern value="[a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="RFCProveedor">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <minLength value="12"/>
         *             <maxLength value="13"/>
         *             <whiteSpace value="collapse"/>
         *             <pattern value="[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="MontoTotalIVA" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
         *       <attribute name="MontoRetencionISR" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
         *       <attribute name="MontoRetencionIVA" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
         *       <attribute name="MontoRetencionOtrosImpuestos" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
         *       <attribute name="NumeroPedimentoVinculado">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <length value="21"/>
         *             <pattern value="[0-9]{2}  [0-9]{2}  [0-9]{4}  [0-9]{7}"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="ClavePedimentoVinculado" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}ClavePedimento" />
         *       <attribute name="ClavePagoPedimentoVinculado" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}ClavePagoPedimento" />
         *       <attribute name="MontoIVAPedimento" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
         *       <attribute name="OtrosImpuestosPagadosPedimento" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
         *       <attribute name="FechaFolioFiscalVinculado">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}date">
         *             <whiteSpace value="collapse"/>
         *             <pattern value="([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Mes" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Meses" />
         *       <attribute name="MontoTotalErogaciones" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DocumentoRelacionado
            implements Serializable
        {

            private static final long serialVersionUID = 1L;
            @XmlAttribute(name = "OrigenErogacion", required = true)
            protected String origenErogacion;
            @XmlAttribute(name = "FolioFiscalVinculado")
            protected String folioFiscalVinculado;
            @XmlAttribute(name = "RFCProveedor")
            protected String rfcProveedor;
            @XmlAttribute(name = "MontoTotalIVA")
            protected BigDecimal montoTotalIVA;
            @XmlAttribute(name = "MontoRetencionISR")
            protected BigDecimal montoRetencionISR;
            @XmlAttribute(name = "MontoRetencionIVA")
            protected BigDecimal montoRetencionIVA;
            @XmlAttribute(name = "MontoRetencionOtrosImpuestos")
            protected BigDecimal montoRetencionOtrosImpuestos;
            @XmlAttribute(name = "NumeroPedimentoVinculado")
            protected String numeroPedimentoVinculado;
            @XmlAttribute(name = "ClavePedimentoVinculado")
            protected String clavePedimentoVinculado;
            @XmlAttribute(name = "ClavePagoPedimentoVinculado")
            protected String clavePagoPedimentoVinculado;
            @XmlAttribute(name = "MontoIVAPedimento")
            protected BigDecimal montoIVAPedimento;
            @XmlAttribute(name = "OtrosImpuestosPagadosPedimento")
            protected BigDecimal otrosImpuestosPagadosPedimento;
            @XmlAttribute(name = "FechaFolioFiscalVinculado")
            protected XMLGregorianCalendar fechaFolioFiscalVinculado;
            @XmlAttribute(name = "Mes", required = true)
            protected String mes;
            @XmlAttribute(name = "MontoTotalErogaciones", required = true)
            protected BigDecimal montoTotalErogaciones;

            /**
             * Gets the value of the origenErogacion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrigenErogacion() {
                return origenErogacion;
            }

            /**
             * Sets the value of the origenErogacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrigenErogacion(String value) {
                this.origenErogacion = value;
            }

            /**
             * Gets the value of the folioFiscalVinculado property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFolioFiscalVinculado() {
                return folioFiscalVinculado;
            }

            /**
             * Sets the value of the folioFiscalVinculado property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFolioFiscalVinculado(String value) {
                this.folioFiscalVinculado = value;
            }

            /**
             * Gets the value of the rfcProveedor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRFCProveedor() {
                return rfcProveedor;
            }

            /**
             * Sets the value of the rfcProveedor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRFCProveedor(String value) {
                this.rfcProveedor = value;
            }

            /**
             * Gets the value of the montoTotalIVA property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMontoTotalIVA() {
                return montoTotalIVA;
            }

            /**
             * Sets the value of the montoTotalIVA property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMontoTotalIVA(BigDecimal value) {
                this.montoTotalIVA = value;
            }

            /**
             * Gets the value of the montoRetencionISR property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMontoRetencionISR() {
                return montoRetencionISR;
            }

            /**
             * Sets the value of the montoRetencionISR property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMontoRetencionISR(BigDecimal value) {
                this.montoRetencionISR = value;
            }

            /**
             * Gets the value of the montoRetencionIVA property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMontoRetencionIVA() {
                return montoRetencionIVA;
            }

            /**
             * Sets the value of the montoRetencionIVA property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMontoRetencionIVA(BigDecimal value) {
                this.montoRetencionIVA = value;
            }

            /**
             * Gets the value of the montoRetencionOtrosImpuestos property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMontoRetencionOtrosImpuestos() {
                return montoRetencionOtrosImpuestos;
            }

            /**
             * Sets the value of the montoRetencionOtrosImpuestos property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMontoRetencionOtrosImpuestos(BigDecimal value) {
                this.montoRetencionOtrosImpuestos = value;
            }

            /**
             * Gets the value of the numeroPedimentoVinculado property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumeroPedimentoVinculado() {
                return numeroPedimentoVinculado;
            }

            /**
             * Sets the value of the numeroPedimentoVinculado property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumeroPedimentoVinculado(String value) {
                this.numeroPedimentoVinculado = value;
            }

            /**
             * Gets the value of the clavePedimentoVinculado property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClavePedimentoVinculado() {
                return clavePedimentoVinculado;
            }

            /**
             * Sets the value of the clavePedimentoVinculado property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClavePedimentoVinculado(String value) {
                this.clavePedimentoVinculado = value;
            }

            /**
             * Gets the value of the clavePagoPedimentoVinculado property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClavePagoPedimentoVinculado() {
                return clavePagoPedimentoVinculado;
            }

            /**
             * Sets the value of the clavePagoPedimentoVinculado property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClavePagoPedimentoVinculado(String value) {
                this.clavePagoPedimentoVinculado = value;
            }

            /**
             * Gets the value of the montoIVAPedimento property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMontoIVAPedimento() {
                return montoIVAPedimento;
            }

            /**
             * Sets the value of the montoIVAPedimento property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMontoIVAPedimento(BigDecimal value) {
                this.montoIVAPedimento = value;
            }

            /**
             * Gets the value of the otrosImpuestosPagadosPedimento property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getOtrosImpuestosPagadosPedimento() {
                return otrosImpuestosPagadosPedimento;
            }

            /**
             * Sets the value of the otrosImpuestosPagadosPedimento property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setOtrosImpuestosPagadosPedimento(BigDecimal value) {
                this.otrosImpuestosPagadosPedimento = value;
            }

            /**
             * Gets the value of the fechaFolioFiscalVinculado property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFechaFolioFiscalVinculado() {
                return fechaFolioFiscalVinculado;
            }

            /**
             * Sets the value of the fechaFolioFiscalVinculado property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFechaFolioFiscalVinculado(XMLGregorianCalendar value) {
                this.fechaFolioFiscalVinculado = value;
            }

            /**
             * Gets the value of the mes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMes() {
                return mes;
            }

            /**
             * Sets the value of the mes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMes(String value) {
                this.mes = value;
            }

            /**
             * Gets the value of the montoTotalErogaciones property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMontoTotalErogaciones() {
                return montoTotalErogaciones;
            }

            /**
             * Sets the value of the montoTotalErogaciones property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMontoTotalErogaciones(BigDecimal value) {
                this.montoTotalErogaciones = value;
            }

        }

    }

}
