//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.gob.sat.cfdi.GastosHidrocarburos10;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.cfdi.GastosHidrocarburos10 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.cfdi.GastosHidrocarburos10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GastosHidrocarburos }
     * 
     * @return
     *     the new instance of {@link GastosHidrocarburos }
     */
    public GastosHidrocarburos createGastosHidrocarburos() {
        return new GastosHidrocarburos();
    }

    /**
     * Create an instance of {@link GastosHidrocarburos.Erogacion }
     * 
     * @return
     *     the new instance of {@link GastosHidrocarburos.Erogacion }
     */
    public GastosHidrocarburos.Erogacion createGastosHidrocarburosErogacion() {
        return new GastosHidrocarburos.Erogacion();
    }

    /**
     * Create an instance of {@link GastosHidrocarburos.Erogacion.CentroCostos }
     * 
     * @return
     *     the new instance of {@link GastosHidrocarburos.Erogacion.CentroCostos }
     */
    public GastosHidrocarburos.Erogacion.CentroCostos createGastosHidrocarburosErogacionCentroCostos() {
        return new GastosHidrocarburos.Erogacion.CentroCostos();
    }

    /**
     * Create an instance of {@link GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos }
     * 
     * @return
     *     the new instance of {@link GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos }
     */
    public GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos createGastosHidrocarburosErogacionCentroCostosYacimientos() {
        return new GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos();
    }

    /**
     * Create an instance of {@link GastosHidrocarburos.Erogacion.Actividades }
     * 
     * @return
     *     the new instance of {@link GastosHidrocarburos.Erogacion.Actividades }
     */
    public GastosHidrocarburos.Erogacion.Actividades createGastosHidrocarburosErogacionActividades() {
        return new GastosHidrocarburos.Erogacion.Actividades();
    }

    /**
     * Create an instance of {@link GastosHidrocarburos.Erogacion.Actividades.SubActividades }
     * 
     * @return
     *     the new instance of {@link GastosHidrocarburos.Erogacion.Actividades.SubActividades }
     */
    public GastosHidrocarburos.Erogacion.Actividades.SubActividades createGastosHidrocarburosErogacionActividadesSubActividades() {
        return new GastosHidrocarburos.Erogacion.Actividades.SubActividades();
    }

    /**
     * Create an instance of {@link GastosHidrocarburos.Erogacion.DocumentoRelacionado }
     * 
     * @return
     *     the new instance of {@link GastosHidrocarburos.Erogacion.DocumentoRelacionado }
     */
    public GastosHidrocarburos.Erogacion.DocumentoRelacionado createGastosHidrocarburosErogacionDocumentoRelacionado() {
        return new GastosHidrocarburos.Erogacion.DocumentoRelacionado();
    }

    /**
     * Create an instance of {@link GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos.Pozos }
     * 
     * @return
     *     the new instance of {@link GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos.Pozos }
     */
    public GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos.Pozos createGastosHidrocarburosErogacionCentroCostosYacimientosPozos() {
        return new GastosHidrocarburos.Erogacion.CentroCostos.Yacimientos.Pozos();
    }

    /**
     * Create an instance of {@link GastosHidrocarburos.Erogacion.Actividades.SubActividades.Tareas }
     * 
     * @return
     *     the new instance of {@link GastosHidrocarburos.Erogacion.Actividades.SubActividades.Tareas }
     */
    public GastosHidrocarburos.Erogacion.Actividades.SubActividades.Tareas createGastosHidrocarburosErogacionActividadesSubActividadesTareas() {
        return new GastosHidrocarburos.Erogacion.Actividades.SubActividades.Tareas();
    }

}
