//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.gob.sat.cfdi.implocal;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.cfdi.implocal package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.cfdi.implocal
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImpuestosLocales }
     * 
     * @return
     *     the new instance of {@link ImpuestosLocales }
     */
    public ImpuestosLocales createImpuestosLocales() {
        return new ImpuestosLocales();
    }

    /**
     * Create an instance of {@link ImpuestosLocales.RetencionesLocales }
     * 
     * @return
     *     the new instance of {@link ImpuestosLocales.RetencionesLocales }
     */
    public ImpuestosLocales.RetencionesLocales createImpuestosLocalesRetencionesLocales() {
        return new ImpuestosLocales.RetencionesLocales();
    }

    /**
     * Create an instance of {@link ImpuestosLocales.TrasladosLocales }
     * 
     * @return
     *     the new instance of {@link ImpuestosLocales.TrasladosLocales }
     */
    public ImpuestosLocales.TrasladosLocales createImpuestosLocalesTrasladosLocales() {
        return new ImpuestosLocales.TrasladosLocales();
    }

}
