//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.gob.sat.cfdi.spei;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="SPEI_Tercero" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <all>
 *                   <element name="Ordenante">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <attribute name="BancoEmisor" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <minLength value="1"/>
 *                                 <maxLength value="40"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Nombre" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <maxLength value="40"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="TipoCuenta" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 <totalDigits value="2"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Cuenta" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 <totalDigits value="20"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="RFC" use="required" type="{http://www.sat.gob.mx/spei}tRFC" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="Beneficiario">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <attribute name="BancoReceptor" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <minLength value="1"/>
 *                                 <maxLength value="40"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Nombre" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <maxLength value="40"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="TipoCuenta" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 <totalDigits value="2"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="Cuenta" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 <totalDigits value="20"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="RFC" use="required" type="{http://www.sat.gob.mx/spei}tRFC" />
 *                           <attribute name="Concepto" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 <maxLength value="40"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="IVA">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 <fractionDigits value="2"/>
 *                                 <totalDigits value="19"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                           <attribute name="MontoPago" use="required">
 *                             <simpleType>
 *                               <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 <minInclusive value="1"/>
 *                                 <totalDigits value="19"/>
 *                                 <fractionDigits value="2"/>
 *                               </restriction>
 *                             </simpleType>
 *                           </attribute>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </all>
 *                 <attribute name="FechaOperacion" use="required">
 *                   <simpleType>
 *                     <restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                       <maxInclusive value="9999-12-31"/>
 *                       <minInclusive value="0001-01-01"/>
 *                       <pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))"/>
 *                     </restriction>
 *                   </simpleType>
 *                 </attribute>
 *                 <attribute name="Hora" use="required">
 *                   <simpleType>
 *                     <restriction base="{http://www.w3.org/2001/XMLSchema}time">
 *                       <pattern value="(([01][0-9])|(2[0-3]))(:[0-5][0-9]){2}(\.[0-9]+)?"/>
 *                     </restriction>
 *                   </simpleType>
 *                 </attribute>
 *                 <attribute name="ClaveSPEI" use="required">
 *                   <simpleType>
 *                     <restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                       <totalDigits value="5"/>
 *                     </restriction>
 *                   </simpleType>
 *                 </attribute>
 *                 <attribute name="sello" use="required">
 *                   <simpleType>
 *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       <whiteSpace value="collapse"/>
 *                     </restriction>
 *                   </simpleType>
 *                 </attribute>
 *                 <attribute name="numeroCertificado" use="required">
 *                   <simpleType>
 *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       <maxLength value="20"/>
 *                       <whiteSpace value="collapse"/>
 *                     </restriction>
 *                   </simpleType>
 *                 </attribute>
 *                 <attribute name="cadenaCDA" use="required">
 *                   <simpleType>
 *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       <maxLength value="841"/>
 *                     </restriction>
 *                   </simpleType>
 *                 </attribute>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "speiTercero"
})
@XmlRootElement(name = "Complemento_SPEI")
public class ComplementoSPEI
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "SPEI_Tercero", required = true)
    protected List<ComplementoSPEI.SPEITercero> speiTercero;

    /**
     * Gets the value of the speiTercero property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the speiTercero property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSPEITercero().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplementoSPEI.SPEITercero }
     * 
     * 
     * @return
     *     The value of the speiTercero property.
     */
    public List<ComplementoSPEI.SPEITercero> getSPEITercero() {
        if (speiTercero == null) {
            speiTercero = new ArrayList<>();
        }
        return this.speiTercero;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <all>
     *         <element name="Ordenante">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <attribute name="BancoEmisor" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <minLength value="1"/>
     *                       <maxLength value="40"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Nombre" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <maxLength value="40"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="TipoCuenta" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       <totalDigits value="2"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Cuenta" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       <totalDigits value="20"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="RFC" use="required" type="{http://www.sat.gob.mx/spei}tRFC" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="Beneficiario">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <attribute name="BancoReceptor" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <minLength value="1"/>
     *                       <maxLength value="40"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Nombre" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <maxLength value="40"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="TipoCuenta" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       <totalDigits value="2"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="Cuenta" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       <totalDigits value="20"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="RFC" use="required" type="{http://www.sat.gob.mx/spei}tRFC" />
     *                 <attribute name="Concepto" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       <maxLength value="40"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="IVA">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       <fractionDigits value="2"/>
     *                       <totalDigits value="19"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *                 <attribute name="MontoPago" use="required">
     *                   <simpleType>
     *                     <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       <minInclusive value="1"/>
     *                       <totalDigits value="19"/>
     *                       <fractionDigits value="2"/>
     *                     </restriction>
     *                   </simpleType>
     *                 </attribute>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </all>
     *       <attribute name="FechaOperacion" use="required">
     *         <simpleType>
     *           <restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *             <maxInclusive value="9999-12-31"/>
     *             <minInclusive value="0001-01-01"/>
     *             <pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))"/>
     *           </restriction>
     *         </simpleType>
     *       </attribute>
     *       <attribute name="Hora" use="required">
     *         <simpleType>
     *           <restriction base="{http://www.w3.org/2001/XMLSchema}time">
     *             <pattern value="(([01][0-9])|(2[0-3]))(:[0-5][0-9]){2}(\.[0-9]+)?"/>
     *           </restriction>
     *         </simpleType>
     *       </attribute>
     *       <attribute name="ClaveSPEI" use="required">
     *         <simpleType>
     *           <restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *             <totalDigits value="5"/>
     *           </restriction>
     *         </simpleType>
     *       </attribute>
     *       <attribute name="sello" use="required">
     *         <simpleType>
     *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             <whiteSpace value="collapse"/>
     *           </restriction>
     *         </simpleType>
     *       </attribute>
     *       <attribute name="numeroCertificado" use="required">
     *         <simpleType>
     *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             <maxLength value="20"/>
     *             <whiteSpace value="collapse"/>
     *           </restriction>
     *         </simpleType>
     *       </attribute>
     *       <attribute name="cadenaCDA" use="required">
     *         <simpleType>
     *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             <maxLength value="841"/>
     *           </restriction>
     *         </simpleType>
     *       </attribute>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class SPEITercero
        implements Serializable
    {

        private static final long serialVersionUID = 1L;
        @XmlElement(name = "Ordenante", required = true)
        protected ComplementoSPEI.SPEITercero.Ordenante ordenante;
        @XmlElement(name = "Beneficiario", required = true)
        protected ComplementoSPEI.SPEITercero.Beneficiario beneficiario;
        @XmlAttribute(name = "FechaOperacion", required = true)
        protected XMLGregorianCalendar fechaOperacion;
        @XmlAttribute(name = "Hora", required = true)
        protected XMLGregorianCalendar hora;
        @XmlAttribute(name = "ClaveSPEI", required = true)
        protected BigInteger claveSPEI;
        @XmlAttribute(name = "sello", required = true)
        protected String sello;
        @XmlAttribute(name = "numeroCertificado", required = true)
        protected String numeroCertificado;
        @XmlAttribute(name = "cadenaCDA", required = true)
        protected String cadenaCDA;

        /**
         * Gets the value of the ordenante property.
         * 
         * @return
         *     possible object is
         *     {@link ComplementoSPEI.SPEITercero.Ordenante }
         *     
         */
        public ComplementoSPEI.SPEITercero.Ordenante getOrdenante() {
            return ordenante;
        }

        /**
         * Sets the value of the ordenante property.
         * 
         * @param value
         *     allowed object is
         *     {@link ComplementoSPEI.SPEITercero.Ordenante }
         *     
         */
        public void setOrdenante(ComplementoSPEI.SPEITercero.Ordenante value) {
            this.ordenante = value;
        }

        /**
         * Gets the value of the beneficiario property.
         * 
         * @return
         *     possible object is
         *     {@link ComplementoSPEI.SPEITercero.Beneficiario }
         *     
         */
        public ComplementoSPEI.SPEITercero.Beneficiario getBeneficiario() {
            return beneficiario;
        }

        /**
         * Sets the value of the beneficiario property.
         * 
         * @param value
         *     allowed object is
         *     {@link ComplementoSPEI.SPEITercero.Beneficiario }
         *     
         */
        public void setBeneficiario(ComplementoSPEI.SPEITercero.Beneficiario value) {
            this.beneficiario = value;
        }

        /**
         * Gets the value of the fechaOperacion property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaOperacion() {
            return fechaOperacion;
        }

        /**
         * Sets the value of the fechaOperacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaOperacion(XMLGregorianCalendar value) {
            this.fechaOperacion = value;
        }

        /**
         * Gets the value of the hora property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getHora() {
            return hora;
        }

        /**
         * Sets the value of the hora property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setHora(XMLGregorianCalendar value) {
            this.hora = value;
        }

        /**
         * Gets the value of the claveSPEI property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getClaveSPEI() {
            return claveSPEI;
        }

        /**
         * Sets the value of the claveSPEI property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setClaveSPEI(BigInteger value) {
            this.claveSPEI = value;
        }

        /**
         * Gets the value of the sello property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSello() {
            return sello;
        }

        /**
         * Sets the value of the sello property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSello(String value) {
            this.sello = value;
        }

        /**
         * Gets the value of the numeroCertificado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumeroCertificado() {
            return numeroCertificado;
        }

        /**
         * Sets the value of the numeroCertificado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumeroCertificado(String value) {
            this.numeroCertificado = value;
        }

        /**
         * Gets the value of the cadenaCDA property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCadenaCDA() {
            return cadenaCDA;
        }

        /**
         * Sets the value of the cadenaCDA property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCadenaCDA(String value) {
            this.cadenaCDA = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <attribute name="BancoReceptor" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <minLength value="1"/>
         *             <maxLength value="40"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Nombre" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <maxLength value="40"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="TipoCuenta" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             <totalDigits value="2"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Cuenta" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             <totalDigits value="20"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="RFC" use="required" type="{http://www.sat.gob.mx/spei}tRFC" />
         *       <attribute name="Concepto" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <maxLength value="40"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="IVA">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             <fractionDigits value="2"/>
         *             <totalDigits value="19"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="MontoPago" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             <minInclusive value="1"/>
         *             <totalDigits value="19"/>
         *             <fractionDigits value="2"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Beneficiario
            implements Serializable
        {

            private static final long serialVersionUID = 1L;
            @XmlAttribute(name = "BancoReceptor", required = true)
            protected String bancoReceptor;
            @XmlAttribute(name = "Nombre", required = true)
            protected String nombre;
            @XmlAttribute(name = "TipoCuenta", required = true)
            protected BigDecimal tipoCuenta;
            @XmlAttribute(name = "Cuenta", required = true)
            protected BigDecimal cuenta;
            @XmlAttribute(name = "RFC", required = true)
            protected String rfc;
            @XmlAttribute(name = "Concepto", required = true)
            protected String concepto;
            @XmlAttribute(name = "IVA")
            protected BigDecimal iva;
            @XmlAttribute(name = "MontoPago", required = true)
            protected BigDecimal montoPago;

            /**
             * Gets the value of the bancoReceptor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBancoReceptor() {
                return bancoReceptor;
            }

            /**
             * Sets the value of the bancoReceptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBancoReceptor(String value) {
                this.bancoReceptor = value;
            }

            /**
             * Gets the value of the nombre property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNombre() {
                return nombre;
            }

            /**
             * Sets the value of the nombre property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNombre(String value) {
                this.nombre = value;
            }

            /**
             * Gets the value of the tipoCuenta property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTipoCuenta() {
                return tipoCuenta;
            }

            /**
             * Sets the value of the tipoCuenta property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTipoCuenta(BigDecimal value) {
                this.tipoCuenta = value;
            }

            /**
             * Gets the value of the cuenta property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getCuenta() {
                return cuenta;
            }

            /**
             * Sets the value of the cuenta property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setCuenta(BigDecimal value) {
                this.cuenta = value;
            }

            /**
             * Gets the value of the rfc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRFC() {
                return rfc;
            }

            /**
             * Sets the value of the rfc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRFC(String value) {
                this.rfc = value;
            }

            /**
             * Gets the value of the concepto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getConcepto() {
                return concepto;
            }

            /**
             * Sets the value of the concepto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConcepto(String value) {
                this.concepto = value;
            }

            /**
             * Gets the value of the iva property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getIVA() {
                return iva;
            }

            /**
             * Sets the value of the iva property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setIVA(BigDecimal value) {
                this.iva = value;
            }

            /**
             * Gets the value of the montoPago property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMontoPago() {
                return montoPago;
            }

            /**
             * Sets the value of the montoPago property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMontoPago(BigDecimal value) {
                this.montoPago = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <attribute name="BancoEmisor" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <minLength value="1"/>
         *             <maxLength value="40"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Nombre" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             <maxLength value="40"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="TipoCuenta" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             <totalDigits value="2"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="Cuenta" use="required">
         *         <simpleType>
         *           <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             <totalDigits value="20"/>
         *           </restriction>
         *         </simpleType>
         *       </attribute>
         *       <attribute name="RFC" use="required" type="{http://www.sat.gob.mx/spei}tRFC" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Ordenante
            implements Serializable
        {

            private static final long serialVersionUID = 1L;
            @XmlAttribute(name = "BancoEmisor", required = true)
            protected String bancoEmisor;
            @XmlAttribute(name = "Nombre", required = true)
            protected String nombre;
            @XmlAttribute(name = "TipoCuenta", required = true)
            protected BigDecimal tipoCuenta;
            @XmlAttribute(name = "Cuenta", required = true)
            protected BigDecimal cuenta;
            @XmlAttribute(name = "RFC", required = true)
            protected String rfc;

            /**
             * Gets the value of the bancoEmisor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBancoEmisor() {
                return bancoEmisor;
            }

            /**
             * Sets the value of the bancoEmisor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBancoEmisor(String value) {
                this.bancoEmisor = value;
            }

            /**
             * Gets the value of the nombre property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNombre() {
                return nombre;
            }

            /**
             * Sets the value of the nombre property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNombre(String value) {
                this.nombre = value;
            }

            /**
             * Gets the value of the tipoCuenta property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTipoCuenta() {
                return tipoCuenta;
            }

            /**
             * Sets the value of the tipoCuenta property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTipoCuenta(BigDecimal value) {
                this.tipoCuenta = value;
            }

            /**
             * Gets the value of the cuenta property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getCuenta() {
                return cuenta;
            }

            /**
             * Sets the value of the cuenta property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setCuenta(BigDecimal value) {
                this.cuenta = value;
            }

            /**
             * Gets the value of the rfc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRFC() {
                return rfc;
            }

            /**
             * Sets the value of the rfc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRFC(String value) {
                this.rfc = value;
            }

        }

    }

}
