//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.gob.sat.cfdi.vehiculousado;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="InformacionAduanera" type="{http://www.sat.gob.mx/vehiculousado}t_InformacionAduanera" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="Version" use="required" fixed="1.0">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="montoAdquisicion" use="required" type="{http://www.sat.gob.mx/vehiculousado}t_Importe" />
 *       <attribute name="montoEnajenacion" use="required" type="{http://www.sat.gob.mx/vehiculousado}t_Importe" />
 *       <attribute name="claveVehicular" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *             <minLength value="1"/>
 *             <maxLength value="7"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="marca" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *             <minLength value="1"/>
 *             <maxLength value="50"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="tipo" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *             <minLength value="1"/>
 *             <maxLength value="50"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="modelo" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *             <pattern value="[0-9]{4}"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="numeroMotor">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *             <minLength value="1"/>
 *             <maxLength value="17"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="numeroSerie">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *             <minLength value="1"/>
 *             <maxLength value="17"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="NIV">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <whiteSpace value="collapse"/>
 *             <minLength value="1"/>
 *             <maxLength value="17"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="valor" use="required" type="{http://www.sat.gob.mx/vehiculousado}t_Importe" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "informacionAduanera"
})
@XmlRootElement(name = "VehiculoUsado")
public class VehiculoUsado
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "InformacionAduanera")
    protected List<TInformacionAduanera> informacionAduanera;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "montoAdquisicion", required = true)
    protected BigDecimal montoAdquisicion;
    @XmlAttribute(name = "montoEnajenacion", required = true)
    protected BigDecimal montoEnajenacion;
    @XmlAttribute(name = "claveVehicular", required = true)
    protected String claveVehicular;
    @XmlAttribute(name = "marca", required = true)
    protected String marca;
    @XmlAttribute(name = "tipo", required = true)
    protected String tipo;
    @XmlAttribute(name = "modelo", required = true)
    protected String modelo;
    @XmlAttribute(name = "numeroMotor")
    protected String numeroMotor;
    @XmlAttribute(name = "numeroSerie")
    protected String numeroSerie;
    @XmlAttribute(name = "NIV")
    protected String niv;
    @XmlAttribute(name = "valor", required = true)
    protected BigDecimal valor;

    /**
     * Gets the value of the informacionAduanera property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the informacionAduanera property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInformacionAduanera().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInformacionAduanera }
     * 
     * 
     * @return
     *     The value of the informacionAduanera property.
     */
    public List<TInformacionAduanera> getInformacionAduanera() {
        if (informacionAduanera == null) {
            informacionAduanera = new ArrayList<>();
        }
        return this.informacionAduanera;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the montoAdquisicion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoAdquisicion() {
        return montoAdquisicion;
    }

    /**
     * Sets the value of the montoAdquisicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMontoAdquisicion(BigDecimal value) {
        this.montoAdquisicion = value;
    }

    /**
     * Gets the value of the montoEnajenacion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoEnajenacion() {
        return montoEnajenacion;
    }

    /**
     * Sets the value of the montoEnajenacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMontoEnajenacion(BigDecimal value) {
        this.montoEnajenacion = value;
    }

    /**
     * Gets the value of the claveVehicular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveVehicular() {
        return claveVehicular;
    }

    /**
     * Sets the value of the claveVehicular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveVehicular(String value) {
        this.claveVehicular = value;
    }

    /**
     * Gets the value of the marca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarca() {
        return marca;
    }

    /**
     * Sets the value of the marca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarca(String value) {
        this.marca = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the modelo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelo() {
        return modelo;
    }

    /**
     * Sets the value of the modelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelo(String value) {
        this.modelo = value;
    }

    /**
     * Gets the value of the numeroMotor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroMotor() {
        return numeroMotor;
    }

    /**
     * Sets the value of the numeroMotor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroMotor(String value) {
        this.numeroMotor = value;
    }

    /**
     * Gets the value of the numeroSerie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroSerie() {
        return numeroSerie;
    }

    /**
     * Sets the value of the numeroSerie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroSerie(String value) {
        this.numeroSerie = value;
    }

    /**
     * Gets the value of the niv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNIV() {
        return niv;
    }

    /**
     * Sets the value of the niv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNIV(String value) {
        this.niv = value;
    }

    /**
     * Gets the value of the valor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValor() {
        return valor;
    }

    /**
     * Sets the value of the valor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValor(BigDecimal value) {
        this.valor = value;
    }

}
