//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.gob.sat.cfdi.Pagos20;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.cfdi.Pagos20 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.cfdi.Pagos20
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pagos }
     * 
     * @return
     *     the new instance of {@link Pagos }
     */
    public Pagos createPagos() {
        return new Pagos();
    }

    /**
     * Create an instance of {@link Pagos.Pago }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago }
     */
    public Pagos.Pago createPagosPago() {
        return new Pagos.Pago();
    }

    /**
     * Create an instance of {@link Pagos.Pago.ImpuestosP }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.ImpuestosP }
     */
    public Pagos.Pago.ImpuestosP createPagosPagoImpuestosP() {
        return new Pagos.Pago.ImpuestosP();
    }

    /**
     * Create an instance of {@link Pagos.Pago.ImpuestosP.TrasladosP }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.ImpuestosP.TrasladosP }
     */
    public Pagos.Pago.ImpuestosP.TrasladosP createPagosPagoImpuestosPTrasladosP() {
        return new Pagos.Pago.ImpuestosP.TrasladosP();
    }

    /**
     * Create an instance of {@link Pagos.Pago.ImpuestosP.RetencionesP }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.ImpuestosP.RetencionesP }
     */
    public Pagos.Pago.ImpuestosP.RetencionesP createPagosPagoImpuestosPRetencionesP() {
        return new Pagos.Pago.ImpuestosP.RetencionesP();
    }

    /**
     * Create an instance of {@link Pagos.Pago.DoctoRelacionado }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.DoctoRelacionado }
     */
    public Pagos.Pago.DoctoRelacionado createPagosPagoDoctoRelacionado() {
        return new Pagos.Pago.DoctoRelacionado();
    }

    /**
     * Create an instance of {@link Pagos.Pago.DoctoRelacionado.ImpuestosDR }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.DoctoRelacionado.ImpuestosDR }
     */
    public Pagos.Pago.DoctoRelacionado.ImpuestosDR createPagosPagoDoctoRelacionadoImpuestosDR() {
        return new Pagos.Pago.DoctoRelacionado.ImpuestosDR();
    }

    /**
     * Create an instance of {@link Pagos.Pago.DoctoRelacionado.ImpuestosDR.TrasladosDR }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.DoctoRelacionado.ImpuestosDR.TrasladosDR }
     */
    public Pagos.Pago.DoctoRelacionado.ImpuestosDR.TrasladosDR createPagosPagoDoctoRelacionadoImpuestosDRTrasladosDR() {
        return new Pagos.Pago.DoctoRelacionado.ImpuestosDR.TrasladosDR();
    }

    /**
     * Create an instance of {@link Pagos.Pago.DoctoRelacionado.ImpuestosDR.RetencionesDR }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.DoctoRelacionado.ImpuestosDR.RetencionesDR }
     */
    public Pagos.Pago.DoctoRelacionado.ImpuestosDR.RetencionesDR createPagosPagoDoctoRelacionadoImpuestosDRRetencionesDR() {
        return new Pagos.Pago.DoctoRelacionado.ImpuestosDR.RetencionesDR();
    }

    /**
     * Create an instance of {@link Pagos.Totales }
     * 
     * @return
     *     the new instance of {@link Pagos.Totales }
     */
    public Pagos.Totales createPagosTotales() {
        return new Pagos.Totales();
    }

    /**
     * Create an instance of {@link Pagos.Pago.ImpuestosP.TrasladosP.TrasladoP }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.ImpuestosP.TrasladosP.TrasladoP }
     */
    public Pagos.Pago.ImpuestosP.TrasladosP.TrasladoP createPagosPagoImpuestosPTrasladosPTrasladoP() {
        return new Pagos.Pago.ImpuestosP.TrasladosP.TrasladoP();
    }

    /**
     * Create an instance of {@link Pagos.Pago.ImpuestosP.RetencionesP.RetencionP }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.ImpuestosP.RetencionesP.RetencionP }
     */
    public Pagos.Pago.ImpuestosP.RetencionesP.RetencionP createPagosPagoImpuestosPRetencionesPRetencionP() {
        return new Pagos.Pago.ImpuestosP.RetencionesP.RetencionP();
    }

    /**
     * Create an instance of {@link Pagos.Pago.DoctoRelacionado.ImpuestosDR.TrasladosDR.TrasladoDR }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.DoctoRelacionado.ImpuestosDR.TrasladosDR.TrasladoDR }
     */
    public Pagos.Pago.DoctoRelacionado.ImpuestosDR.TrasladosDR.TrasladoDR createPagosPagoDoctoRelacionadoImpuestosDRTrasladosDRTrasladoDR() {
        return new Pagos.Pago.DoctoRelacionado.ImpuestosDR.TrasladosDR.TrasladoDR();
    }

    /**
     * Create an instance of {@link Pagos.Pago.DoctoRelacionado.ImpuestosDR.RetencionesDR.RetencionDR }
     * 
     * @return
     *     the new instance of {@link Pagos.Pago.DoctoRelacionado.ImpuestosDR.RetencionesDR.RetencionDR }
     */
    public Pagos.Pago.DoctoRelacionado.ImpuestosDR.RetencionesDR.RetencionDR createPagosPagoDoctoRelacionadoImpuestosDRRetencionesDRRetencionDR() {
        return new Pagos.Pago.DoctoRelacionado.ImpuestosDR.RetencionesDR.RetencionDR();
    }

}
