//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.gob.sat.cfdi.terceros;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.cfdi.terceros package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.cfdi.terceros
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros }
     * 
     * @return
     *     the new instance of {@link PorCuentadeTerceros }
     */
    public PorCuentadeTerceros createPorCuentadeTerceros() {
        return new PorCuentadeTerceros();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.InformacionFiscalTercero }
     * 
     * @return
     *     the new instance of {@link PorCuentadeTerceros.InformacionFiscalTercero }
     */
    public PorCuentadeTerceros.InformacionFiscalTercero createPorCuentadeTercerosInformacionFiscalTercero() {
        return new PorCuentadeTerceros.InformacionFiscalTercero();
    }

    /**
     * Create an instance of {@link TUbicacionFiscal }
     * 
     * @return
     *     the new instance of {@link TUbicacionFiscal }
     */
    public TUbicacionFiscal createTUbicacionFiscal() {
        return new TUbicacionFiscal();
    }

    /**
     * Create an instance of {@link TInformacionAduanera }
     * 
     * @return
     *     the new instance of {@link TInformacionAduanera }
     */
    public TInformacionAduanera createTInformacionAduanera() {
        return new TInformacionAduanera();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.InformacionFiscalTercero.InformacionAduanera }
     * 
     * @return
     *     the new instance of {@link PorCuentadeTerceros.InformacionFiscalTercero.InformacionAduanera }
     */
    public PorCuentadeTerceros.InformacionFiscalTercero.InformacionAduanera createPorCuentadeTercerosInformacionFiscalTerceroInformacionAduanera() {
        return new PorCuentadeTerceros.InformacionFiscalTercero.InformacionAduanera();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.InformacionFiscalTercero.Parte }
     * 
     * @return
     *     the new instance of {@link PorCuentadeTerceros.InformacionFiscalTercero.Parte }
     */
    public PorCuentadeTerceros.InformacionFiscalTercero.Parte createPorCuentadeTercerosInformacionFiscalTerceroParte() {
        return new PorCuentadeTerceros.InformacionFiscalTercero.Parte();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.InformacionFiscalTercero.CuentaPredial }
     * 
     * @return
     *     the new instance of {@link PorCuentadeTerceros.InformacionFiscalTercero.CuentaPredial }
     */
    public PorCuentadeTerceros.InformacionFiscalTercero.CuentaPredial createPorCuentadeTercerosInformacionFiscalTerceroCuentaPredial() {
        return new PorCuentadeTerceros.InformacionFiscalTercero.CuentaPredial();
    }

}
